### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/errors' is not defined by "exports" in next-auth/package.json

### ISSUE THREAD

**Issue by kioltk** [nextauthjs/adapters#105]
Greetings.

Struggled by connecting next-auth and Prisma a lot of time, found out that the whole example does not work with current Prisma adapter release.

Reproduction [repo is here](https://github.com/kioltk/next-auth-typescript-example).

Reproduction steps: 
1. Fork [next-auth-typescript-example](https://github.com/nextauthjs/next-auth-typescript-example)
2. Proceed by adding Prisma by [docs guide](https://next-auth.js.org/adapters/prisma)
3. Run `yarn dev`
4. Click the **Sign In**
5. See the error in browser:
<img width="964" alt="TypeError: providers is not an Object. (evaluating 'provider in providers')
" src="https://user-images.githubusercontent.com/5237220/119591308-0be75a00-bddf-11eb-88bf-b57f96f3cfbb.png">

6. See the error in console: 
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/errors' is not defined by "exports" in /Users/david/dev/playground/next-auth-typescript-example/node_modules/next-auth/package.json
    at new NodeError (node:internal/errors:329:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:337:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:562:3)
    at resolveExports (node:internal/modules/cjs/loader:473:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:513:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:27)
    at Function.mod._resolveFilename (/Users/david/dev/playground/next-auth-typescript-example/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/david/dev/playground/next-auth-typescript-example/node_modules/@next-auth/prisma-adapter/dist/index.js:54:16)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I like how the console points on [the exact line](https://github.com/nextauthjs/adapters/blob/892c4f760cebe48c73447715d41fab4ef14ec71e/packages/prisma/src/index.ts#L8) of code [marked](https://github.com/nextauthjs/adapters/commit/40f45f55bbcb00ba7ed2beed48bd421a9ad933a7) by @williamluke4  as `// !TODO Expose 'errors' and 'logger' in next-auth`

Haven't found anything related, sorry if its duplicate.

**Comment by balazsorban44** [comment]
You seem to be on a 4 months old release, could you give `0.4.4-canary.57` a try instead? Check the actual source code here: https://github.com/nextauthjs/adapters/blob/canary/packages/prisma/src/index.ts

**Comment by hlz** [comment]
Having the same issue I can confirm `0.4.4-canary.57` does indeed work. Maybe it should be a bit more clear in the docs that this adapter is a wip and canary should be used.

**Comment by balazsorban44** [comment]
@ndom91 I wonder if we could change the badges in the main readme, so they point to the latest canary versions until we close #68?

https://github.com/nextauthjs/adapters#adapters

**Comment by ndom91** [comment]
Yeah that makes a lot of sense, PR incoming!

**Comment by kioltk** [comment]
@balazsorban44 thanks for your quick response! 

Yeah, the whole issue was about missing proper documentation, cause even if I looked all over the docs and git, I haven't noticed canary
