### ISSUE TITLE
Use new prisma adapter  and get  [get_user_by_provider_account_id_error] [{"clientVersion":"2.15.0"}] 

### ISSUE THREAD

**Issue by mynlexi** [nextauthjs/adapters#120]
**Your question**
How do i get rid of this error?

in the issue nextauthjs/next-auth#1166, the consensus seems to be that this issue is solved with the canary build.

my error message:
[next-auth][error][get_user_by_provider_account_id_error] [{"clientVersion":"2.15.0"}] 
https://next-auth.js.org/errors#get_user_by_provider_account_id_error
[next-auth][error][oauth_callback_handler_error] [{}] 
https://next-auth.js.org/errors#oauth_callback_handler_error

**What are you trying to do**
authenticating with githubconnect

**Reproduction**

My versions:
"@prisma/cli": "^2.15.0",
    "@prisma/client": "^2.15.0",
    "next": "10.0.5",
    "next-auth": "^3.2.0-canary.36",

My schema:
```prisma
model Quiz {
  id        Int      @default(autoincrement()) @id
  title     String
  question  String
  points    Int
  answer_1  String 
  
}

model Account {
  id                 Int       @id @default(autoincrement())
  userId             Int
  providerType       String
  providerId         String
  providerAccountId  String
  refreshToken       String?
  accessToken        String?
  accessTokenExpires DateTime?
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  user               User      @relation(fields: [userId], references: [id])

  @@unique([providerId, providerAccountId])
}

model Session {
  id           Int      @id @default(autoincrement())
  userId       Int
  expires      DateTime
  sessionToken String   @unique
  accessToken  String   @unique
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  user         User     @relation(fields: [userId], references: [id])
}

model User {
  id            Int       @id @default(autoincrement())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  accounts      Account[]
  sessions      Session[]
  quizs         Quiz[]
}

model VerificationRequest {
  id         Int      @id @default(autoincrement())
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}
```

from the adapter doc [here](https://github.com/nextauthjs/adapters/blob/canary/packages/prisma/README.md)

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
#105 #115 #118

**Comment by thecodelearner** [comment]
> @thecodelearner see #105 #115 #118

apologies if this is redundant again, although I've gone through the three linked issues, and seems it's a different problem now:

```
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error Error: 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      providerId: 'google',
      providerAccountId: '********876014'
    }
  },
  select: {
    user: true
  }
}

Unknown arg `providerId_providerAccountId` in where.providerId_providerAccountId for type AccountWhereUniqueInput. Available args:

type AccountWhereUniqueInput {
  id?: String
  Account.providerId_providerAccountId_unique?: AccountAccount.providerId_providerAccountId_uniqueCompoundUniqueInput
}


    at Document.validate (/Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:32776:19)
    at NewPrismaClient._executeRequest (/Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:34718:17)
    at /Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:34653:52
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at NewPrismaClient._request (/Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:34653:25)
    at Object.then (/Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:34773:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  name: 'GetUserByProviderAccountIdError'
```

**Comment by balazsorban44** [comment]
If it's a new issue, I suggest you open a new bug report, with a reproduction.

**Comment by thecodelearner** [comment]
> If it's a new issue, I suggest you open a new bug report, with a reproduction.

fixed this by updating the `schema.prisma` as mentioned in the canary docs here: https://next-auth-git-canary-nextauthjs.vercel.app/schemas/adapters 

thanks a lot for your speedy help @balazsorban44 !

**Comment by balazsorban44** [comment]
Awesome!

**Comment by magisters-cc** [comment]
2021-09-18T11:55:28.169Z	c1326cc9-4a56-4acd-a4a2-bc570f80d788	ERROR	[next-auth][error][prisma_legacy__get_user_by_provider_account_id_error] 
https://next-auth.js.org/errors#prisma_legacy__get_user_by_provider_account_id_error PrismaClientValidationError: Unknown arg `compoundId` in where.compoundId for type AccountWhereUniqueInput.
    at Document.validate (/var/task/node_modules/@prisma/client/runtime/index.js:35604:19)
    at PrismaClient._executeRequest (/var/task/node_modules/@prisma/client/runtime/index.js:37991:17)
    at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:37936:23)
    at /var/task/node_modules/@prisma/client/runtime/index.js:37938:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:37938:25)
    at request (/var/task/node_modules/@prisma/client/runtime/index.js:38041:77)
    at _callback (/var/task/node_modules/@prisma/client/runtime/index.js:38246:14)
    at PrismaPromise.then (/var/task/node_modules/@prisma/client/runtime/index.js:38253:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  clientVersion: '3.0.2'
}
2021-09-18T11:55:28.169Z	c1326cc9-4a56-4acd-a4a2-bc570f80d788	ERROR	[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error Error: Unknown arg `compoundId` in where.compoundId for type AccountWhereUniqueInput.
    at Document.validate (/var/task/node_modules/@prisma/client/runtime/index.js:35604:19)
    at PrismaClient._executeRequest (/var/task/node_modules/@prisma/client/runtime/index.js:37991:17)
    at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:37936:23)
    at /var/task/node_modules/@prisma/client/runtime/index.js:37938:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:37938:25)
    at request (/var/task/node_modules/@prisma/client/runtime/index.js:38041:77)
    at _callback (/var/task/node_modules/@prisma/client/runtime/index.js:38246:14)
    at PrismaPromise.then (/var/task/node_modules/@prisma/client/runtime/index.js:38253:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  name: 'GetUserByProviderAccountIdError'
}

Get this error when using latest Next Auth docs.

**Comment by kushthakker** [comment]
`[next-auth][error][prisma__get_user_by_provider_account_id_error] 
https://next-auth.js.org/errors#prisma__get_user_by_provider_account_id_error PrismaClientValidationError: 
Invalid `prisma.account.findUnique()` invocation in
/Users/kushthakker/projects/testingawsapi/node_modules/@next-auth/prisma-adapter/dist/index.js:41:58

  38 },
  39 async getUserByProviderAccountId(providerId, providerAccountId) {
  40     var _a;
→ 41     const account = await prisma.account.findUnique({
           where: {
             providerId_providerAccountId: {
               providerId: 'github',
               providerAccountId: 43739786
                                  ~~~~~~~~
             }
           },
           select: {
             user: true
           }
         })

Argument providerAccountId: Got invalid value 43739786 on prisma.findUniqueAccount. Provided Int, expected String.


    at Object.validate (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:34787:20)
    at PrismaClient._executeRequest (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39581:17)
    at consumer (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39522:23)
    at /Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39526:49
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at PrismaClient._request (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39526:27)
    at request (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39631:77)
    at _callback (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39839:14)
    at PrismaPromise.then (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39846:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  clientVersion: '3.3.0'
}
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error Error: 
Invalid `prisma.account.findUnique()` invocation in
/Users/kushthakker/projects/testingawsapi/node_modules/@next-auth/prisma-adapter/dist/index.js:41:58

  38 },
  39 async getUserByProviderAccountId(providerId, providerAccountId) {
  40     var _a;
→ 41     const account = await prisma.account.findUnique({
           where: {
             providerId_providerAccountId: {
               providerId: 'github',
               providerAccountId: 43739786
                                  ~~~~~~~~
             }
           },
           select: {
             user: true
           }
         })

Argument providerAccountId: Got invalid value 43739786 on prisma.findUniqueAccount. Provided Int, expected String.


    at Object.validate (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:34787:20)
    at PrismaClient._executeRequest (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39581:17)
    at consumer (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39522:23)
    at /Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39526:49
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at PrismaClient._request (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39526:27)
    at request (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39631:77)
    at _callback (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39839:14)
    at PrismaPromise.then (/Users/kushthakker/projects/testingawsapi/node_modules/@prisma/client/runtime/index.js:39846:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  name: 'GetUserByProviderAccountIdError'
}
`

Getting this error and can't find any way to solve it.

**Comment by balazsorban44** [comment]
Please don't comment on an already closed issue with your problem, it creates maintenance noise. Open a new issue and refer to the old one instead.
