### ISSUE TITLE
TypeError: _next_auth_prisma_adapter__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function

### ISSUE THREAD

**Issue by Xenfo** [nextauthjs/adapters#137]
Tried with `0.4.4-canary.64` and `0.4.4` to no avail. Though `0.4.4` gives errors from #105.

Error:
```
TypeError: _next_auth_prisma_adapter__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
    at eval (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:16:76)
    at Object../src/pages/api/auth/[...nextauth].ts (/home/xenfo/Desktop/Projects/xenfodotdev/.next/server/pages/api/auth/[...nextauth].js:32:1)
    at __webpack_require__ (/home/xenfo/Desktop/Projects/xenfodotdev/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/xenfo/Desktop/Projects/xenfodotdev/.next/server/pages/api/auth/[...nextauth].js:86:52)
    at /home/xenfo/Desktop/Projects/xenfodotdev/.next/server/pages/api/auth/[...nextauth].js:87:116
    at Object.<anonymous> (/home/xenfo/Desktop/Projects/xenfodotdev/.next/server/pages/api/auth/[...nextauth].js:90:3)
```

**Comment by balazsorban44** [comment]
Please provide a reproduction

**Comment by Xenfo** [comment]
Got it to work, I did a bad import
