### ISSUE TITLE
Possible prisma adapter incompatablity

### ISSUE THREAD

**Issue by callumgare** [nextauthjs/adapters#160]
I'm sure I'm just making a silly mistake here but I'm running into an issue which certainly looks like the latest (working, see #159) package for the prisma adapter and next-auth are incomparable. 

```
https://next-auth.js.org/errors#prisma__link_account_error PrismaClientValidationError: 
Invalid `prisma.account.create()` invocation:

{
  data: {
    userId: undefined,
+   providerType: String,
+   providerId: String,
+   providerAccountId: String,
+   user: {
+     create?: UserCreateWithoutAccountsInput | UserUncheckedCreateWithoutAccountsInput,
+     connectOrCreate?: UserCreateOrConnectWithoutAccountsInput,
+     connect?: UserWhereUniqueInput
+   },
?   id?: String,
?   refreshToken?: String | null,
?   accessToken?: String | null,
?   accessTokenExpires?: DateTime | null,
?   createdAt?: DateTime,
?   updatedAt?: DateTime
  }
}

Argument providerType for data.providerType is missing.
Argument providerId for data.providerId is missing.
Argument providerAccountId for data.providerAccountId is missing.
Argument user for data.user is missing.

Note: Lines with + are required, lines with ? are optional.
```

When I dig into the source code it _looks like_ next-auth is calling the prisma adapter's linkAccount function with the incorrect signature

https://unpkg.com/browse/next-auth@3.27.1/dist/server/lib/callback-handler.js#L133

https://unpkg.com/browse/@next-auth/prisma-adapter@0.5.0/dist/index.js#L36

I'm using the exact prisma schema listed in the documentation (https://next-auth.js.org/adapters/prisma):

```
model Account {
  id                 String    @id @default(cuid())
  userId             String
  providerType       String
  providerId         String
  providerAccountId  String
  refreshToken       String?
  accessToken        String?
  accessTokenExpires DateTime?
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  user               User      @relation(fields: [userId], references: [id])

  @@unique([providerId, providerAccountId])
}
```

Am I missing something here or they actually not compatible?

**Comment by balazsorban44** [comment]
:grimacing: Something very funky is going on...

https://github.com/nextauthjs/adapters/blob/a625df6dbc10cc2ddbe3bd400be965b7f1ccd780/packages/prisma/src/index.ts#L78-L98

Here is the actual source code for `linkAccount`! The code that seemingly got to unpkg.com is something I have been working on locally, for our next major release 🤕. I think this issue happened when at some point, we experimented with `lerna`, and I did a publish from my local machine, and I probably did not stash my changes. 😅 I cannot say sorry enough! :pray: I'll try to get to the bottom of the empty release in `0.5.1`, and hopefully `0.5.2`(?) should fix these problems...!

**Comment by zuhair-naqvi** [comment]
@balazsorban44 what do you recommend in the mean time? Can you please git-patch a git patch so we can use with patch-package?

**Comment by callumgare** [comment]
@balazsorban44 Thanks for that, glad I'm not crazy at least :P

**Comment by balazsorban44** [comment]
Try downgrading. I am at work the whole day unfortunately, I cannot look at it before tonight.

**Comment by ndom91** [comment]
@issue we just published new `@latest` versions of all adapters from the latest `main` branch code. Should be good to go again. Can you please give the latest release of your adapter a shot? Thanks!

**Comment by siddharthsharma94** [comment]
Circling back on this, i actually just got a similar error @ndom91 

I'm getting ```Argument providerAccountId: Got invalid value 11656847 on prisma.findUniqueAccount. Provided Int, expected String.```

I pretty much copied and pasted from the guide on the main docs site for the Prisma adaptor.

Full error

```bash
Argument providerAccountId: Got invalid value 11656847 on prisma.findUniqueAccount. Provided Int, expected String.


    at Document.validate (/Users/sidd/Documents/Personal-Apps/open-source/source/node_modules/@prisma/client/runtime/index.js:32626:19)
    at NewPrismaClient._executeRequest (/Users/sidd/Documents/Personal-Apps/open-source/source/node_modules/@prisma/client/runtime/index.js:34733:17)
    at consumer (/Users/sidd/Documents/Personal-Apps/open-source/source/node_modules/@prisma/client/runtime/index.js:34678:23)
    at /Users/sidd/Documents/Personal-Apps/open-source/source/node_modules/@prisma/client/runtime/index.js:34680:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (/Users/sidd/Documents/Personal-Apps/open-source/source/node_modules/@prisma/client/runtime/index.js:34680:25)
    at Object.then (/Users/sidd/Documents/Personal-Apps/open-source/source/node_modules/@prisma/client/runtime/index.js:34788:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'GetUserByProviderAccountIdError'
}
```

**Comment by ndom91** [comment]
@siddharthsharma94 are you using GitHub as an oauth provider by chance?

**Comment by siddharthsharma94** [comment]
@ndom91 Yup I am

**Comment by ndom91** [comment]
Okay im pretty sure it's this issue: https://github.com/nextauthjs/adapters/issues/130

There's a workaround at the bottom. 
 
This is fixed generally in the v4 dev branch of next-auth, but unfortunately it's a breaking change so we didn't want to roll it out in a minor/patch.

**Comment by ndom91** [comment]
I'm going to close this issue, the original mistake deploy is fixed and the GitHub id type issue was something else. 

If anyone still has issues, feel free to reopen or create a new issue.
