### ISSUE TITLE
Custom model won't work

### ISSUE THREAD

**Issue by dev-goutham** [nextauthjs/adapters#169]
### Description 🐜

Hey, I'm trying to extend the User model for my mongo database, I followed the following tutorial: https://next-auth.js.org/tutorials/typeorm-custom-models

When I pass the custom User model to NextAuth, it's showing the following error: 
```Type '{ User: { model: TypeORMUserModel; schema: EntitySchemaOptions<TypeORMUserModel>; }; }' is missing the following properties from type 'TypeORMAdapterModels': Account, Session, VerificationRequest```

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

My custom User model:

```js
import Adapters, { TypeORMUserModel } from 'next-auth/adapters'

export default class UserModel extends TypeORMUserModel {
	constructor(
		name?: string,
		email?: string,
		image?: string,
		emailVerified?: Date
	) {
		super(name, email, image, emailVerified)
	}
}

type Schema = typeof Adapters.TypeORM.Models.User.schema

export const UserSchema: Schema = {
	name: 'User',
	target: UserModel,
	columns: {
		...Adapters.TypeORM.Models.User.schema.columns,
		isAdmin: {
			type: 'boolean',
			nullable: false,
			default: false,
		},
	},
}

```

My auth/[...nextauth].tsx:
```js
import Models from '@/backend/models'
import NextAuth, { NextAuthOptions } from 'next-auth'
import Adapters from 'next-auth/adapters'
import Providers from 'next-auth/providers'

const options: NextAuthOptions = {
	providers: [
		Providers.Google({
			clientId: process.env.GOOGLE_OAUTH_CLIENT_ID,
			clientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
		}),
	],
	database: process.env.MONGO_URI,
	debug: process.env.NODE_ENV === 'development',
	secret: process.env.AUTH_SECRET,
	adapter: Adapters.TypeORM.Adapter(process.env.MONGO_URI!, {
		models: {
			User: Models.User,
		},
	}),
}

export default NextAuth(options)

```

### Screenshots / Logs 📽

![Screenshot (3)](https://user-images.githubusercontent.com/74486872/125740774-6c9079e3-8ad7-441c-8d90-55eb07f58f4e.png)

### Environment 🖥

 System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 5.69 GB / 9.27 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.14.0/bin/yarn
    npm: 7.11.1 - ~/.nvm/versions/node/v15.14.0/bin/npm
  npmPackages:
    next: ^11.0.1 => 11.0.1
    next-auth: ^3.27.2 => 3.27.2
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Seems very similar to https://github.com/nextauthjs/adapters/issues/168 but I think it is not a duplicate. You only seem to have a TypeScript issue, is that correct? (using `// @ts-ignore` resolves the issue?)

**Comment by dev-goutham** [comment]
@balazsorban44 No, it doesn't.  The following error is thrown on server side when I try to authenticate.

```
TypeError: Class extends value undefined is not a constructor or null
    at Module../src/backend/models/User.ts (/home/goutham/files/code/e-commerce/.next/server/pages/api/auth/[...nextauth].js:28:73)
    at __webpack_require__ (/home/goutham/files/code/e-commerce/.next/server/webpack-runtime.js:25:43)
    at Module../src/backend/models/index.ts (/home/goutham/files/code/e-commerce/.next/server/pages/api/auth/[...nextauth].js:56:63)
    at __webpack_require__ (/home/goutham/files/code/e-commerce/.next/server/webpack-runtime.js:25:43)
    at Module../src/pages/api/auth/[...nextauth]/index.ts (/home/goutham/files/code/e-commerce/.next/server/pages/api/auth/[...nextauth].js:75:73)
    at __webpack_require__ (/home/goutham/files/code/e-commerce/.next/server/webpack-runtime.js:25:43)
    at __webpack_exec__ (/home/goutham/files/code/e-commerce/.next/server/pages/api/auth/[...nextauth].js:143:52)
    at /home/goutham/files/code/e-commerce/.next/server/pages/api/auth/[...nextauth].js:144:28
    at Object.<anonymous> (/home/goutham/files/code/e-commerce/.next/server/pages/api/auth/[...nextauth].js:147:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at DevServer.handleApiRequest (/home/goutham/files/code/e-commerce/node_modules/next/dist/next-server/server/next-server.js:66:181)
```

**Comment by balazsorban44** [comment]
I see. I wonder if it is because of this change https://github.com/nextauthjs/adapters/pull/87/files

@ndom91 this seems to be a breaking change as the constructor has changed. Should we revert it? :grimacing:

**Comment by ndom91** [comment]
Hmm but has the constructor changed? It just got refactored from individual field checks to optional chaining, right? Not sure why the account, session, verificationRequest relationships would be missing.

**Comment by dev-goutham** [comment]
Okay I figured it out. If anyone's still struggling with it, here's how you do it. The documentation is either wrong or severely out of date. Also there seem to be some issues with a few typescript typing.

models/User.ts
```
import Adapters from 'next-auth/adapters'

export default class UserModel extends (<any>(
	Adapters.TypeORM.Models.User.model
)) {
	public customField: type

	constructor(
		name?: string,
		email?: string,
		image?: string,
		emailVerified?: Date,
		customeFiled= default-value
	) {
		super(name, email, image, emailVerified)
		this.customField= customField
	}
}

type Schema = typeof Adapters.TypeORM.Models.User.schema

export const UserSchema: Schema = {
	name: 'User',
	target: UserModel,
	columns: {
		...Adapters.TypeORM.Models.User.schema.columns,
		isAdmin: {
			type: 'boolean',
			nullable: false,
			default: false,
		},
	},
}

```

But if you pass this model to NextAuth.adapters.models it will throw an error saying it's missing Session, Account and VerificationRequest models. So unfortunately we'll have to create those models in the same way we created User model but without any custom fields. Just copy past the following code and save yourself some time.

models/Session.ts

```
import Adapters from 'next-auth/adapters'

export default class SessionModel extends (<any>(
	Adapters.TypeORM.Models.Session.model
)) {
	constructor(
		userId: number,
		expires: Date,
		sessionToken?: string,
		accessToken?: string
	) {
		super(userId, expires, sessionToken, accessToken)
	}
}

type Schema = typeof Adapters.TypeORM.Models.Session.schema

export const SessionSchema: Schema = {
	name: 'Session',
	target: SessionModel,
	columns: {
		...Adapters.TypeORM.Models.Session.schema.columns,
	},
}

```

models/Account.ts
```
import Adapters from 'next-auth/adapters'

export default class AccountModel extends (<any>(
	Adapters.TypeORM.Models.Account.model
)) {
	constructor(
		userId: number,
		providerId: string,
		providerType: string,
		providerAccountId: string,
		refreshToken?: string,
		accessToken?: string,
		accessTokenExpires?: Date
	) {
		super(
			userId,
			providerId,
			providerType,
			providerAccountId,
			refreshToken,
			accessToken,
			accessTokenExpires
		)
	}
}

type Schema = typeof Adapters.TypeORM.Models.Account.schema

export const AccountSchema: Schema = {
	name: 'Account',
	target: AccountModel,
	columns: {
		...Adapters.TypeORM.Models.Account.schema.columns,
	},
}

```

models/VerificationRequest.ts
```
import Adapters from 'next-auth/adapters'

export default class VerificationRequestModel extends (<any>(
	Adapters.TypeORM.Models.VerificationRequest.model
)) {
	constructor(identifier: string, token: string, expires: Date) {
		super(identifier, token, expires)
	}
}

type Schema = typeof Adapters.TypeORM.Models.VerificationRequest.schema

export const VerificationRequestSchema: Schema = {
	name: 'VerificationRequest',
	target: VerificationRequestModel,
	columns: {
		...Adapters.TypeORM.Models.VerificationRequest.schema.columns,
	},
}

```

api/auth/[...nextAuth.ts]
```
import Models from '@/backend/models'
import NextAuth, { NextAuthOptions } from 'next-auth'
import Adapters from 'next-auth/adapters'
import Providers from 'next-auth/providers'

const options: NextAuthOptions = {
	providers: [
		Providers.Google({
			clientId: process.env.GOOGLE_OAUTH_CLIENT_ID,
			clientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
		}),
	],
	database: process.env.MONGO_URI,
	debug: process.env.NODE_ENV === 'development',
	secret: process.env.AUTH_SECRET,
	adapter: Adapters.TypeORM.Adapter(process.env.MONGO_URI!, {
		models: {
			User: Models.User,
			Session: Models.Session,
			Account: Models.Account,
			VerificationRequest: Models.VerificationRequest,
		},
	}),
}

export default NextAuth(options)
```

**Comment by balazsorban44** [comment]
You don't need to override models you don't need to change. You can see it in the source code, that we merge your models with the default ones:

https://github.com/nextauthjs/adapters/blob/main/packages/typeorm-legacy/src/index.js#L20-L23
