### ISSUE TITLE
Prisma adapter expects a string

### ISSUE THREAD

**Issue by ottobenjamin** [nextauthjs/adapters#176]
When I use the Prisma adapter with GitHub as provider, I get the following error.

```[next-auth][error][prisma__get_user_by_provider_account_id_error] 
https://next-auth.js.org/errors#prisma__get_user_by_provider_account_id_error PrismaClientValidationError: 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'github',
      providerAccountId: 00000000
                         ~~~~~~~~
    }
  },
  select: {
    user: true
  }
}

Argument providerAccountId: Got invalid value 00000000 on prisma.findUniqueAccount. Provided Int, expected String.


    at Document.validate (/home/benjamin/luas/node_modules/@prisma/client/runtime/index.js:33530:19)
    at NewPrismaClient._executeRequest (/home/benjamin/luas/node_modules/@prisma/client/runtime/index.js:35637:17)
    at consumer (/home/benjamin/luas/node_modules/@prisma/client/runtime/index.js:35582:23)
    at /home/benjamin/luas/node_modules/@prisma/client/runtime/index.js:35584:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (/home/benjamin/luas/node_modules/@prisma/client/runtime/index.js:35584:25)
    at Object.then (/home/benjamin/luas/node_modules/@prisma/client/runtime/index.js:35692:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  clientVersion: '2.28.0'
}
```

Did I make a mistake or do we need a fix?

I think a change in the schema or in the adapter could lead to incompatibility with other providers that provide the id as string.

The way to fix would be to cast the id of the GitHub provider to a string.
https://github.com/nextauthjs/next-auth/blob/e3c2c7756daa3511a208a07f5b0ee231d8ae9486/src/providers/github.js#L13

**Comment by balazsorban44** [comment]
Duplicate. Please use the search feature to look for ols issues before opening a new one. 😊

**Comment by ottobenjamin** [comment]
Im so sorry 🙈 i was in a hurry and totally forgot to remove the is:open filter. Feel free to remove this issue from the repository.

**Comment by balazsorban44** [comment]
No problem, thanks for understanding!
