### ISSUE TITLE
Google Auth + Prisma not working

### ISSUE THREAD

**Issue by MatteoGauthier** [nextauthjs/adapters#187]
Got an error while attempting to use Google Auth with Prisma adapter.

On deletion and on signin.

```
[next-auth][error][signout_error]
https://next-auth.js.org/errors#signout_error Error:
Invalid `prisma.session.delete()` invocation:

{
  where: {
?   sessionToken?: String,
?   id?: String,
?   accessToken?: String
  }
}

Argument where of type SessionWhereUniqueInput needs at least one argument. Available args are listed in green.

Note: Lines with ? are optional.

    at Document.validate (D:\WorkFolder\Devlopment\Tests\NextJs\rest-nextjs-api-routes\node_modules\@prisma\client\runtime\index.js:35104:19)
    at PrismaClient._executeRequest (D:\WorkFolder\Devlopment\Tests\NextJs\rest-nextjs-api-routes\node_modules\@prisma\client\runtime\index.js:37409:17)
    at consumer (D:\WorkFolder\Devlopment\Tests\NextJs\rest-nextjs-api-routes\node_modules\@prisma\client\runtime\index.js:37354:23)
    at D:\WorkFolder\Devlopment\Tests\NextJs\rest-nextjs-api-routes\node_modules\@prisma\client\runtime\index.js:37356:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at PrismaClient._request (D:\WorkFolder\Devlopment\Tests\NextJs\rest-nextjs-api-routes\node_modules\@prisma\client\runtime\index.js:37356:25)
    at request (D:\WorkFolder\Devlopment\Tests\NextJs\rest-nextjs-api-routes\node_modules\@prisma\client\runtime\index.js:37459:77)
    at Object.then (D:\WorkFolder\Devlopment\Tests\NextJs\rest-nextjs-api-routes\node_modules\@prisma\client\runtime\index.js:37474:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  name: 'DeleteSessionError'
}
```

**Comment by balazsorban44** [comment]
Have a repro?
