### ISSUE TITLE
Enrich user table with additional fields when user authenticates against LinkedIn

### ISSUE THREAD

**Issue by AydinChavez** [nextauthjs/adapters#219]
### Description 🐜

Hi all,

my goal is quite simple: I want to add more than just name, image and email to the user table like username, firstName and lastName.

I use next-auth with prisma adapter for this and extended the schema accordingly with those three additional fields:
```
model User {
  id            String    @id @default(cuid())
  name          String
  firstName     String?
  lastName      String?
  username      String?
  email         String    @unique
  emailVerified DateTime?
  image         String?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  accounts      Account[]
  sessions      Session[]
  password      String?
}
```
Added the field mapping in the async profile method (in [nextauth.ts]) accordingly and the next-auth debug logging looks quite promising:

```
[next-auth][debug][prisma__create_user] {
  id: 'kSJbJSlAfr',
  name: 'Aydin Chavez',
  firstName: 'Aydin',
  lastName: 'Chavez',
  email: 'aydin.chavez@gmail.com',
  image: 'https://...',
  username: 'aydin-chavez-ksjbjslafr'
}
```

But in the createUser event, those fields have all null values when logging in via linkedIn.

Meaning a debug console.log in the createUser event:

```
events: {
    createUser: async (message) => {
      console.log("createUser: " + JSON.stringify(message, null, 2));
     },
  },
```

leads suddenly to this output (having null for the three fields):

```
createUser: {
  "id": "ckthq7p820006f1s4k6hj8yd6",
  "name": "Aydin Chavez",
  "firstName": null,
  "lastName": null,
  "username": null,
  "email": "aydin.chavez@gmail.com",
  "emailVerified": null,
  "image": "https://...",
  "createdAt": "2021-09-12T21:25:23.954Z",
  "updatedAt": "2021-09-12T21:25:23.954Z",
  "password": null
}
```

Did I miss something or is this functionality not supported yet?

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

see above

### Environment 🖥

```
  System:
    OS: macOS 11.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 566.22 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.2
  npmPackages:
    next: ^11.1.0 => 11.1.0
    next-auth: 3.28.0 => 3.28.0
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Hi, you are on the right track! However this is not a bug, rather a limitation of `next-auth` v3 architectural decisions. The v3 compatible adapters only saved those basic fields you see not saved as `null`. We intended to fix this in a pr #132 but it backfired #151, so we reverted it #166

However the v4 compatible adapters don't have the same constraint, and with properly documenting it (so people will understand that the `profile` callback of your Provider will determine the required DB schema https://next-auth.js.org/adapters/models#user), we can simply forward all the properties passed to the `createUser` method to the underlying DB.

Your options are:
1. Upgrade to v4, and your expectations will match the reality. See the migration guide: https://next-auth.js.org/getting-started/upgrade-v4 (not, v4 is in beta)
2. create your own adapter, similar to #132

**Comment by AydinChavez** [comment]
@balazsorban44 Thanks a lot for the detailled and helpful response. I'll try out v4 beta tomorrow and let you know about the results.

Regarding your side questions on pw in db: Currently I am offering email based login, password based login and delegated LinkedIn/Oauth2 login. I am aware that the next-auth project by design does not recommend password based authentication due to security concerns. In my case I am not sure if this functionality will be kept in my project once it'll go live next year, however I give my best to implement it in a relatively secure fashion (passwords being hashed with argon2 algorithm for example). Reason why not using third-party provider is because I don't want to forward the users to a third-party page because of workflow interruption and design concerns (e.g. redirect on external page might slow down user registration or different branding/design of external page might irritate user). If you have a suggestion of third-party services for storing passwords which is includable seamlessly in my next.js project I look forward for suggestions.

**Comment by balazsorban44** [comment]
Sounds good! As long as you are aware, it's up to you. :wink:

Keep me posted on how the migration goes.

**Comment by AydinChavez** [comment]
I made some progress with the migration to 4.0.0-beta.2

Now to issues are happening:

**1) Auth with LinkedIn - following error is returned (do I need to update prisma schema)?**


```
[next-auth][debug][adapter_getUserByAccount] { args: [ { providerAccountId: 'kSJbJSlAfr', provider: 'linkedin' } ] }
[next-auth][error][adapter_error_getUserByAccount]
https://next-auth.js.org/errors#adapter_error_getuserbyaccount
Invalid prisma.account.findUnique() invocation:

{
  where: {
    provider_providerAccountId: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
      providerAccountId: 'kSJbJSlAfr',
      provider: 'linkedin'
    }
  },
  select: {
    user: true
  }
}

Unknown arg 'provider_providerAccountId' in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean 'providerId_providerAccountId'? Available args:
type AccountWhereUniqueInput {
  id?: String
  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
}

 {
  message: '\n' +
    'Invalid 'prisma.account.findUnique()' invocation:\n' +
    '\n' +
    '{\n' +
    '  where: {\n' +
    '    provider_providerAccountId: {\n' +
    '    ~~~~~~~~~~~~~~~~~~~~~~~~~~\n' +
    "      providerAccountId: 'kSJbJSlAfr',\n" +
    "      provider: 'linkedin'\n" +
    '    }\n' +
    '  },\n' +
    '  select: {\n' +
    '    user: true\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'Unknown arg 'provider_providerAccountId' in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean 'providerId_providerAccountId'? Available args:\n' +
    'type AccountWhereUniqueInput {\n' +
    '  id?: String\n' +
    '  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput\n' +
    '}\n' +
    '\n',
  stack: 'Error: \n' +
    'Invalid 'prisma.account.findUnique()' invocation:\n' +
    '\n' +
    '{\n' +
    '  where: {\n' +
    '    provider_providerAccountId: {\n' +
    '    ~~~~~~~~~~~~~~~~~~~~~~~~~~\n' +
    "      providerAccountId: 'kSJbJSlAfr',\n" +
    "      provider: 'linkedin'\n" +
    '    }\n' +
    '  },\n' +
    '  select: {\n' +
    '    user: true\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'Unknown arg 'provider_providerAccountId' in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean 'providerId_providerAccountId'? Available args:\n' +
    'type AccountWhereUniqueInput {\n' +
    '  id?: String\n' +
    '  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput\n' +
    '}\n' +
    '\n' +
    '\n' +
    '    at Document.validate (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:35604:19)\n' +
    '    at PrismaClient._executeRequest (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:37991:17)\n' +
    '    at consumer (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:37936:23)\n' +
    '    at /Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:37938:47\n' +
    '    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)\n' +
    '    at PrismaClient._request (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:37938:25)\n' +
    '    at request (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:38041:77)\n' +
    '    at _callback (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:38246:14)\n' +
    '    at PrismaPromise.then (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:38253:23)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error
Invalid prisma.account.findUnique() invocation:

{
  where: {
    provider_providerAccountId: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
      providerAccountId: 'kSJbJSlAfr',
      provider: 'linkedin'
    }
  },
  select: {
    user: true
  }
}

Unknown arg 'provider_providerAccountId' in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean 'providerId_providerAccountId'? Available args:
type AccountWhereUniqueInput {
  id?: String
  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
}

 Error:
Invalid 'prisma.account.findUnique()' invocation:

{
  where: {
    provider_providerAccountId: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
      providerAccountId: 'kSJbJSlAfr',
      provider: 'linkedin'
    }
  },
  select: {
    user: true
  }
}

Unknown arg 'provider_providerAccountId' in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean 'providerId_providerAccountId'? Available args:
type AccountWhereUniqueInput {
  id?: String
  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
}


    at Document.validate (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:35604:19)
    at PrismaClient._executeRequest (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:37991:17)
    at consumer (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:37936:23)
    at /Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:37938:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at PrismaClient._request (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:37938:25)
    at request (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:38041:77)
    at _callback (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:38246:14)
    at PrismaPromise.then (/Users/aydinchavez/Workspace/projectxyz/node_modules/@prisma/client/runtime/index.js:38253:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  name: 'GetUserByAccountError'
}'
```

**2) Credentials login returns** an error:

`Error: HTTP POST is not supported for /api/auth/callback/credentials`

My setup is:

```
CredentialsProvider({
      id: "username-login", // <- add this line
      name: "Login",
      authorize: async (credentials) => {
        const user = await getUserByPassword(credentials)
        return user;
      },
      credentials: {
        email: { label: "E-Mail", type: "text ", placeholder: "email" },
        password: {
          label: "Password",
          type: "password",
          placeholder: "a-really-long-password",
        },
      },
    }),
```

I am executing the signIn in the the login form. It worked with version 3x, so I assume it's migration related but don't know how to restructure the CredentialsProvider to get it working.

login.js

```
import { useState } from "react";
import { signIn, useSession } from "next-auth/react"
import { env } from '@/constants/env'

export default function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    // "username-login" matches the id for the credential
    signIn("username-login", { username, password, callbackUrl: env.NEXTAUTH_URL });
  };

  return (
        <form onSubmit={handleSubmit}>
          <div>
            <label htmlFor="username">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              placeholder="Username"
              onChange={(e) => setUsername(e.target.value)}
              value={username}
            />
          </div>
          <div>
            <label htmlFor="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="Password"
              onChange={(e) => setPassword(e.target.value)}
              value={password}
            />
          </div>
          <button type="submit">
            Login
          </button>
        </form>
  );
}
```

**Comment by balazsorban44** [comment]
1. the schema has changed slightly, yes. See the new fields expected here:

https://next-auth.js.org/adapters/models

I believe you simply have to migrate `providerId` to `provider`.

I think we can document the schema changes better. I might have been over optimistic in my statement here that users won't need changing anything for the new adapter API https://next-auth.js.org/getting-started/upgrade-v4#adapter-api 

cc @ndom91

2. that's strange, I'll have to investigate

**Comment by AydinChavez** [comment]
for 1) Just renaming providerId to provider did not work out, I had to do more adjustments in the schema file based on your given reference model.

Ended up with:

```
model Account {
  id                 String    @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
  refresh_token       String?
  access_token       String?   @db.VarChar(1024)
  expires_at         Int?
  token_type         String?
  id_token           String?
  scope              String?
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  user               User      @relation(fields: [userId], references: [id])

  @@unique([provider, providerAccountId])
}
```

However, am not sure if 
  token_type         String?
  id_token           String?
  scope              String?
are needed at all, because they're null (but listed in the model diagram at https://next-auth.js.org/adapters/models)


Now the new fields are present in the token, but not in the session.
3) Also quite lot of objects are null, concrete I mean when doing a console debug output here:

 ```
   jwt: async ({ token, user, account, profile, isNewUser }) => {
..

      console.log("jwt:token: " + JSON.stringify(token, null, 2));
      console.log("jwt:account: " + JSON.stringify(account, null, 2));
      console.log("jwt:user: "+ JSON.stringify(user, null, 2));
      console.log("jwt:profile: "+ JSON.stringify(profile, null, 2));
      console.log("jwt:isNewUser: "+ JSON.stringify(isNewUser, null, 2));

```

I get - good:

```
jwt:token: {
  "name": "Aydin Chavez",
  "email": "aydin.chavez@gmail.com",
  "picture": "https://....",
  "sub": "cktifpn0c0009f7s406guqulr",
  "image": "https://....",
  "firstname": "Aydin",
  "iat": 1631524752,
  "exp": 1634116752
}
```

bad: 
```
jwt:account: undefined
jwt:user: undefined
jwt:profile: undefined
jwt:isNewUser: undefined
```


Similar for session object, when doing debug outputs here:

```
  session: async ({ session, token, user }) => {
      console.log("session:session "+ JSON.stringify(session, null, 2));
      console.log("session:user: "+ JSON.stringify(user, null, 2));
      session.firstname = token.firstname
      return Promise.resolve({
        ...session,
        user: {
          ...user,
        },
      })
    },
```

I get 

good:
```
session:session {
  "user": {
    "name": "Aydin Chavez",
    "email": "aydin.chavez@gmail.com",
    "image": "https://.."
  },
  "expires": "2021-10-13T09:19:31.577Z"
}
```

bad: `session:user: undefined`
bad: missing firstname

**Comment by balazsorban44** [comment]
When you use a database persisted session, the JWT callback shouldn't be invoked at all.

**Comment by AydinChavez** [comment]
Allright, thank you. Do you want me to create separate issues for the ones above or do you know if somebody is having a look already on a fix?

**Comment by balazsorban44** [comment]
For what? What do you mean?

**Comment by AydinChavez** [comment]
So far I counted four issues or unsolved topic in this thread with v4 beta:

**1) Credentials login returns:**

`Error: HTTP POST is not supported for /api/auth/callback/credentials`

My setup is:

```js
CredentialsProvider({
      id: "username-login", // <- add this line
      name: "Login",
      authorize: async (credentials) => {
        const user = await getUserByPassword(credentials)
        return user;
      },
      credentials: {
        email: { label: "E-Mail", type: "text ", placeholder: "email" },
        password: {
          label: "Password",
          type: "password",
          placeholder: "a-really-long-password",
        },
      },
    }),
```

I am executing the signIn in the the login form. It worked with version 3x, so I assume it's migration related but don't know how to restructure the CredentialsProvider to get it working.

login.js

```js
import { useState } from "react";
import { signIn, useSession } from "next-auth/react"
import { env } from '@/constants/env'

export default function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    // "username-login" matches the id for the credential
    signIn("username-login", { username, password, callbackUrl: env.NEXTAUTH_URL });
  };

  return (
        <form onSubmit={handleSubmit}>
          <div>
            <label htmlFor="username">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              placeholder="Username"
              onChange={(e) => setUsername(e.target.value)}
              value={username}
            />
          </div>
          <div>
            <label htmlFor="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="Password"
              onChange={(e) => setPassword(e.target.value)}
              value={password}
            />
          </div>
          <button type="submit">
            Login
          </button>
        </form>
  );
}
```

**2) jwt callback returns null for account, user, profile and isNewUser**

```
jwt: async ({ token, user, account, profile, isNewUser }) => {
     console.log("jwt:token: " + JSON.stringify(token, null, 2));
     console.log("jwt:account: " + JSON.stringify(account, null, 2));
     console.log("jwt:user: "+ JSON.stringify(user, null, 2));
     console.log("jwt:profile: "+ JSON.stringify(profile, null, 2));
     console.log("jwt:isNewUser: "+ JSON.stringify(isNewUser, null, 2));..
..
```

prints:
```
jwt:account: undefined
jwt:user: undefined
jwt:profile: undefined
jwt:isNewUser: undefined
```

**3) session object is undefined in user callback**

```
  session: async ({ session, token, user }) => {
      console.log("session:session "+ JSON.stringify(session, null, 2));
      console.log("session:user: "+ JSON.stringify(user, null, 2));
      session.firstname = token.firstname
      return Promise.resolve({
        ...session,
        user: {
          ...user,
        },
      })
    }
..
```

prints:
```session:user: undefined```

I think this user is experiencing same issue with v4 beta:

https://github.com/nextauthjs/next-auth/issues/2746 

**4) side topic - using jwt and database at once**
I am using JWT and database for persistence. Is this not allowed (independently if it makes sense or not)? If it's not allowed the framework should reject this setup. If it's allowed, the jwt callback should not return null for the objects (see 2 above)

**Comment by balazsorban44** [comment]
1) As said, that makes sense, you don't have a provider that should handle `/api/auth/callback/credentials` Let's open a bug report on this with a CodeSandbox/ GitHub repo reproduction that I can check out on my computer

2) Those other properties are only present at sign-in, but not when you use a Credentials provider. There is no account or profile, just a user (again, only for the first time). Documented here: https://next-auth.js.org/configuration/callbacks#jwt-callback

3) `user` is not defined when you use a JWT persisted session (which you always do when using Credentials provider, it is by design). Use `token` instead. Documented here: https://next-auth.js.org/configuration/callbacks#session-callback

4) You can use a database to persist user data and use JWT to persist sessions at the same time. When you use a Credentials provider, you automatically only use JWT sessions.

**Comment by AydinChavez** [comment]
Thanks for the detailed response.

For 2. and 3. I am not using Credentials provider (it does not work with v4 beta, see 1), I used LinkedIn all the time. Therefore I assume that 2. and 3. next-auth should return valid objects, right?

**Comment by theocampbell** [comment]
I am having the same problem as above. The user object in my session is empty. My set up is:
next auth 4.0.0-beta.6 with credentials provider. 
my user details are stored in a mongo db with hashed passwords. 
when a user signs in using a custom sign in for the username and password are sent to the authorize credentials endpoint in [...nextauth}.js. 
the hashed passwords are then verified using an api and the user id and user name are sent back and stored as user in [...nextauth]. 
this is working for loggin in and loggin out however there is nothing inside the session user object. 
Not sure if a solution has been found for this?

**Comment by theocampbell** [comment]
my form
````
import { useState } from "react";
import { useRouter } from "next/router";
import Layout from "./layout";
import styles from "./../styles/_main.module.scss";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import { signIn } from "next-auth/react"
 

const Form = ({ usermId, userForm, forNewUser = true, csrfToken }) => {
  const router = useRouter();
  const contentType = "application/json";
  const [errors, setErrors] = useState({});
  const [message, setMessage] = useState("");
/*
  const [form, setForm] = useState({
    username: userForm.username,
    password: userForm.password,
  });
*/
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')

//need to add error checking and password restrictions. 
  const onFormSubmit = async (e) => {
    e.preventDefault();

    signIn('credentials', {
      username: username, 
      password: password, 
      redirect: true,
      callbackUrl:  'http://localhost:3000/indexEdit'    })
}

  return (
    <Layout>
      <>
        <Container className={styles.form_container}>
          <Row className={styles.form_row}>
            <Col className={styles.form_col} xs={8}>
              <form className={styles.form_element} onSubmit={onFormSubmit}>
                <h1 className={styles.form_title}>
                  Welcome, please sign in
                </h1>
                <label htmlFor="User">Enter your username</label>

                <input
                  className={styles.form_input}
                  type="text"
                  maxLength="20"
                  name="username"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  // onChange={handleChange}
                  required
                />

                <label htmlFor="password">Enter password</label>
                <input
                  className={styles.form_input}
                  type="password"
                  name="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  // onChange={handleChange}
                  required
                />

                <button className={styles.form_button} type="submit">
                  Sign in
                </button>
              </form>
              <p>{message}</p>
              <div>
                {Object.keys(errors).map((err, index) => (
                  <li key={index}>{err}</li>
                ))}
              </div>
            </Col>
          </Row>
        </Container>
      </>
    </Layout>
  );
};
export default Form;
````
[...nextauth} file

```
import NextAuth from "next-auth"
import CredentialsProvider from "next-auth/providers/credentials"


export default NextAuth({
  providers: [
    CredentialsProvider({
        // The name to display on the sign in form (e.g. 'Sign in with...')
        name: 'Credentials',
 
        
        async authorize(credentials, req) {
          const contentType = "application/json";
          const res = await fetch("http://localhost:3000/api/users/auth", {
          method: 'POST',
          body: JSON.stringify(credentials),
          headers:  {"Content-Type": contentType }
        })
        const user = await res.json()
        console.log(user)
        
          // If no error and we have user data, return it
          if (res.ok && user)
           {
            return user
          }
          // Return null if user data could not be retrieved
          return null
        }
      })
     ],
  session: {
    jwt: true,
    maxAge: 30 * 24 * 60 * 60
  },
  jwt: {
    secret: 'ndsionvuibvjiabvjdisa'
  },
  pages: {
    signIn: 'auth/signin',
    error: 'auth/signin',
    signOut: '/'
  },
})
````

**Comment by balazsorban44** [comment]
there is no solution, it is intended. https://next-auth.js.org/configuration/providers/credentials
