### ISSUE TITLE
More info on adapter_error_getsessionanduser

### ISSUE THREAD

**Issue by fandy** [nextauthjs/adapters#254]
I noticed that v4 doesn't have full documentation for the error messages. Was wondering if someone could explain what's going on with this error:

```
[next-auth][error][adapter_error_getSessionAndUser] 
https://next-auth.js.org/errors#adapter_error_getsessionanduser 
Invalid `prisma.session.findUnique()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(451), routine: Some("StorePreparedStatement") }) }) }) {
  message: '\n' +
    'Invalid `prisma.session.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    '  Error occurred during query execution:\n' +
    'ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \\"s0\\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(451), routine: Some("StorePreparedStatement") }) }) })',
  stack: 'Error: \n' +
    'Invalid `prisma.session.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    '  Error occurred during query execution:\n' +
    'ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \\"s0\\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(451), routine: Some("StorePreparedStatement") }) }) })\n' +
    '    at cb (/Users/fang/Projects/mammal-app/node_modules/@prisma/client/runtime/index.js:36944:17)\n' +
    '    at async getSessionAndUser (/Users/fang/Projects/mammal-app/node_modules/@next-auth/prisma-adapter/dist/index.js:22:36)\n' +
    '    at async acc.<computed> (webpack-internal:///./node_modules/next-auth/server/errors.js:92:16)\n' +
    '    at async Object.session (webpack-internal:///./node_modules/next-auth/server/routes/session.js:83:28)\n' +
    '    at async NextAuthHandler (webpack-internal:///./node_modules/next-auth/server/index.js:145:16)\n' +
    '    at async eval (webpack-internal:///./node_modules/next-auth/server/index.js:251:32)\n' +
    '    at async Object.apiResolver (/Users/fang/Projects/mammal-app/node_modules/next/dist/server/api-utils.js:101:9)\n' +
    '    at async DevServer.handleApiRequest (/Users/fang/Projects/mammal-app/node_modules/next/dist/server/next-server.js:770:9)\n' +
    '    at async Object.fn (/Users/fang/Projects/mammal-app/node_modules/next/dist/server/next-server.js:661:37)\n' +
    '    at async Router.execute (/Users/fang/Projects/mammal-app/node_modules/next/dist/server/router.js:205:32)',
  name: 'Error'
}
[next-auth][error][SESSION_ERROR] 
https://next-auth.js.org/errors#session_error 
Invalid `prisma.session.findUnique()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(451), routine: Some("StorePreparedStatement") }) }) }) Error: 
Invalid `prisma.session.findUnique()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(451), routine: Some("StorePreparedStatement") }) }) })
    at cb (/Users/fang/Projects/mammal-app/node_modules/@prisma/client/runtime/index.js:36944:17)
    at async getSessionAndUser (/Users/fang/Projects/mammal-app/node_modules/@next-auth/prisma-adapter/dist/index.js:22:36)
    at async acc.<computed> (webpack-internal:///./node_modules/next-auth/server/errors.js:92:16)
    at async Object.session (webpack-internal:///./node_modules/next-auth/server/routes/session.js:83:28)
    at async NextAuthHandler (webpack-internal:///./node_modules/next-auth/server/index.js:145:16)
    at async eval (webpack-internal:///./node_modules/next-auth/server/index.js:251:32)
    at async Object.apiResolver (/Users/fang/Projects/mammal-app/node_modules/next/dist/server/api-utils.js:101:9)
    at async DevServer.handleApiRequest (/Users/fang/Projects/mammal-app/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/Users/fang/Projects/mammal-app/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/Users/fang/Projects/mammal-app/node_modules/next/dist/server/router.js:205:32) {
  name: 'GetSessionAndUserError'
}
```
Authentication was working one night and not the next. Trying to debug if there's something up with the connection, but passing `debug: true` doesn't give me useful logs.

**Comment by balazsorban44** [comment]
quick Google sent me here https://github.com/prisma/prisma/issues/4752#issuecomment-767101410
