### ISSUE TITLE
Unique constraint of session after clearing cookies

### ISSUE THREAD

**Issue by proevilz** [nextauthjs/adapters#295]
### Title

Unique constraint of session after clearing cookies

### How to reproduce ☕️

Setup the latest version of next-auth and follow the docs for the Prisma adapter and use the github provider.

### Your question/bug report 📓

When signing in for the first time, everything will be persisted to the database as normal. But if you clear your cookies and attempt to re-login using the same Github account, next-auth/prisma adapter will attempt to re-create a new session and persist it to the database however, as per the [Prisma Schema requirements](https://next-auth.js.org/adapters/prisma) outlined in the docs, the `userId` field is set as unique and as a result, it will throw an error when attempting to store a new session (rather than using/updating the existing one) 

> → 31 createSession: (data) => p.session.create(
  Unique constraint failed on the constraint: `Session_userId_key` {
```
next-auth][error][adapter_error_createSession]
https://next-auth.js.org/errors#adapter_error_createsession
Invalid `p.session.create()` invocation in
/Users/proevilz/sites/myproject/node_modules/@next-auth/prisma-adapter/dist/index.js:31:44

  28     const { user, ...session } = userAndSession;
  29     return { user, session };
  30 },
→ 31 createSession: (data) => p.session.create(
  Unique constraint failed on the constraint: `Session_userId_key` {
  message: '\n' +
    'Invalid `p.session.create()` invocation in\n' +
    '/Users/proevilz/sites/myproject/node_modules/@next-auth/prisma-adapter/dist/index.js:31:44\n' +
    '\n' +
    '  28     const { user, ...session } = userAndSession;\n' +
    '  29     return { user, session };\n' +
    '  30 },\n' +
    '→ 31 createSession: (data) => p.session.create(\n' +
    '  Unique constraint failed on the constraint: `Session_userId_key`',
  stack: 'Error: \n' +
    'Invalid `p.session.create()` invocation in\n' +
    '/Users/proevilz/sites/myproject/node_modules/@next-auth/prisma-adapter/dist/index.js:31:44\n' +
    '\n' +
    '  28     const { user, ...session } = userAndSession;\n' +
    '  29     return { user, session };\n' +
    '  30 },\n' +
    '→ 31 createSession: (data) => p.session.create(\n' +
    '  Unique constraint failed on the constraint: `Session_userId_key`\n' +
    '    at cb (/Users/proevilz/sites/myproject/node_modules/@prisma/client/runtime/index.js:38504:17)\n' +
    '    at async acc.<computed> (/Users/proevilz/sites/myproject/node_modules/next-auth/core/errors.js:92:16)\n' +
    '    at async callbackHandler (/Users/proevilz/sites/myproject/node_modules/next-auth/core/lib/callback-handler.js:136:38)\n' +
    '    at async Object.callback (/Users/proevilz/sites/myproject/node_modules/next-auth/core/routes/callback.js:117:13)\n' +
    '    at async NextAuthHandler (/Users/proevilz/sites/myproject/node_modules/next-auth/core/index.js:103:28)\n' +
    '    at async NextAuthNextHandler (/Users/proevilz/sites/myproject/node_modules/next-auth/next/index.js:40:7)\n' +
    '    at async /Users/proevilz/sites/myproject/node_modules/next-auth/next/index.js:80:32\n' +
    '    at async Object.apiResolver (/Users/proevilz/sites/myproject/node_modules/next/dist/server/api-utils.js:102:9)\n' +
    '    at async DevServer.handleApiRequest (/Users/proevilz/sites/myproject/node_modules/next/dist/server/next-server.js:1014:9)\n' +
    '    at async Object.fn (/Users/proevilz/sites/myproject/node_modules/next/dist/server/next-server.js:901:37)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error
Invalid `p.session.create()` invocation in
/Users/proevilz/sites/myproject/node_modules/@next-auth/prisma-adapter/dist/index.js:31:44

  28     const { user, ...session } = userAndSession;
  29     return { user, session };
  30 },
→ 31 createSession: (data) => p.session.create(
  Unique constraint failed on the constraint: `Session_userId_key` Error:
Invalid `p.session.create()` invocation in
/Users/proevilz/sites/myproject/node_modules/@next-auth/prisma-adapter/dist/index.js:31:44

  28     const { user, ...session } = userAndSession;
  29     return { user, session };
  30 },
→ 31 createSession: (data) => p.session.create(
  Unique constraint failed on the constraint: `Session_userId_key`
    at cb (/Users/proevilz/sites/myproject/node_modules/@prisma/client/runtime/index.js:38504:17)
    at async acc.<computed> (/Users/proevilz/sites/myproject/node_modules/next-auth/core/errors.js:92:16)
    at async callbackHandler (/Users/proevilz/sites/myproject/node_modules/next-auth/core/lib/callback-handler.js:136:38)
    at async Object.callback (/Users/proevilz/sites/myproject/node_modules/next-auth/core/routes/callback.js:117:13)
    at async NextAuthHandler (/Users/proevilz/sites/myproject/node_modules/next-auth/core/index.js:103:28)
    at async NextAuthNextHandler (/Users/proevilz/sites/myproject/node_modules/next-auth/next/index.js:40:7)
    at async /Users/proevilz/sites/myproject/node_modules/next-auth/next/index.js:80:32
    at async Object.apiResolver (/Users/proevilz/sites/myproject/node_modules/next/dist/server/api-utils.js:102:9)
    at async DevServer.handleApiRequest (/Users/proevilz/sites/myproject/node_modules/next/dist/server/next-server.js:1014:9)
    at async Object.fn (/Users/proevilz/sites/myproject/node_modules/next/dist/server/next-server.js:901:37) {
  name: 'CreateSessionError'
}
```

prisma schema being used 
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Post {
  id         String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt  DateTime  @default(now())
  title      String
  body       String
  published  Boolean   @default(false)
  author     User      @relation(fields: [authorId], references: [id])
  authorId   String    @db.ObjectId
  categories Category  @default(POST)
  comments   Comment[]
}

model Comment {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now())
  content   String
  author    User     @relation(fields: [authorId], references: [id])
  authorId  String   @db.ObjectId
  Post      Post?    @relation(fields: [postId], references: [id])
  postId    String?  @db.ObjectId
}

model User {
  id            String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt     DateTime  @default(now())
  email         String    @unique
  username      String?
  name          String?
  role          Role      @default(USER)
  posts         Post[]
  profile       Profile?
  Comment       Comment[]
  Banned        Boolean   @default(false)
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

model Profile {
  id          String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  about       String
  headerImage String
  user        User   @relation(fields: [userId], references: [id])
  userId      String @unique @db.ObjectId
}

model Account {
  id                       String  @id @default(dbgenerated()) @map("_id") @db.ObjectId
  userId                   String  @unique @db.ObjectId
  type                     String
  provider                 String
  providerAccountId        String
  refresh_token            String?
  access_token             String?
  expires_at               Int?
  token_type               String?
  scope                    String?
  id_token                 String?
  session_state            String?
  oauth_token_secret       String?
  oauth_token              String?
  refresh_token_expires_in Int?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  sessionToken String   @unique
  userId       String   @unique @db.ObjectId
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model VerificationToken {
  id         String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

enum Role {
  USER
  MOD
  ADMIN
}

enum Category {
  POST
  IMAGE
  LINK
}
```

I can fix this behavior by setting the `userId` not to be unique in the schema...

### Contributing  🙌🏽

Yes, I am

**Comment by proevilz** [comment]
Misread the docs.
