### ISSUE TITLE
Getting many errors related to the MongoDB Adapter

### ISSUE THREAD

**Issue by callumok2004** [nextauthjs/adapters#297]
### Title

Getting many errors related to the MongoDB Adapter

### How to reproduce ☕️

```ts
import axios from "axios";
import { Db, ObjectId } from "mongodb";
import NextAuth from "next-auth";
import Discord from "next-auth/providers/discord";

import { MongoDBAdapter } from "@next-auth/mongodb-adapter";

import clientPromise from "../../../lib/database";

export default async function auth(req, res) {
  const db = await clientPromise,
    instance: Db = db.db("Ryft-Auth")

  return await NextAuth(req, res, {
    providers: [
      {
        id: "discord",
        name: "Discord",
        type: "oauth",
        authorization: "https://discord.com/api/oauth2/authorize?scope=identify+email",
        token: "https://discord.com/api/oauth2/token",
        userinfo: "https://discord.com/api/users/@me",
        profile(profile, tokens) {
          if (profile.avatar === null) {
            const defaultAvatarNumber = parseInt(profile.discriminator) % 5
            profile.image_url = `https://cdn.discordapp.com/embed/avatars/${defaultAvatarNumber}.png`
          } else {
            const format = profile.avatar.startsWith("a_") ? "gif" : "png"
            profile.image_url = `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.${format}`
          }

          return {
            id: profile.id,
            name: profile.username,
            email: profile.email,
            image: profile.image_url,
          }
        },
        clientId: process.env.DISCORD_ID,
        clientSecret: process.env.DISCORD_SECRET
      }
    ],
    pages: {
      signIn: "/dashboard",
      error: "/auth/error"
    },
    adapter: MongoDBAdapter({
      db: () => instance,
      ObjectId
    })
  })
}
```

### Your question/bug report 📓

```c
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount Cannot read properties of undefined (reading 'getUser') {
  message: "Cannot read properties of undefined (reading 'getUser')",
  stack: "TypeError: Cannot read properties of undefined (reading 'getUser')\n" +
    '    at getUserByAccount (E:\\Developing\\Ryft\\Website-Main\\node_modules\\@next-auth\\mongodb-adapter\\dist\\index.js:64:37)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async acc.<computed> (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\core\\errors.js:92:16)\n' +
    '    at async Object.callback (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\core\\routes\\callback.js:81:33)\n' +
    '    at async NextAuthHandler (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\core\\index.js:103:28)\n' +
    '    at async NextAuthNextHandler (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\next\\index.js:40:7)\n' +
    '    at async auth (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:18:12)\n' +
    '    at async Object.apiResolver (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next\\dist\\server\\api-utils.js:102:9)\n' +
    '    at async DevServer.handleApiRequest (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next\\dist\\server\\next-server.js:1014:9)\n' + 
    '    at async Object.fn (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next\\dist\\server\\next-server.js:901:37)',
  name: 'TypeError'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error Cannot read properties of undefined (reading 'getUser') TypeError: Cannot read properties of undefined (reading 'getUser')
    at getUserByAccount (E:\Developing\Ryft\Website-Main\node_modules\@next-auth\mongodb-adapter\dist\index.js:64:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async acc.<computed> (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\errors.js:92:16)
    at async Object.callback (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\routes\callback.js:81:33)
    at async NextAuthHandler (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\index.js:103:28)
    at async NextAuthNextHandler (E:\Developing\Ryft\Website-Main\node_modules\next-auth\next\index.js:40:7)
    at async auth (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:18:12)
    at async Object.apiResolver (E:\Developing\Ryft\Website-Main\node_modules\next\dist\server\api-utils.js:102:9)
    at async DevServer.handleApiRequest (E:\Developing\Ryft\Website-Main\node_modules\next\dist\server\next-server.js:1014:9)
    at async Object.fn (E:\Developing\Ryft\Website-Main\node_modules\next\dist\server\next-server.js:901:37) {
  name: 'GetUserByAccountError'
}
wait  - compiling /auth/[error]...
event - compiled successfully in 97 ms (262 modules)
[next-auth][error][adapter_error_getSessionAndUser] 
https://next-auth.js.org/errors#adapter_error_getsessionanduser Cannot read properties of undefined (reading 'getUser') {
  message: "Cannot read properties of undefined (reading 'getUser')",
  stack: "TypeError: Cannot read properties of undefined (reading 'getUser')\n" +
    '    at getSessionAndUser (E:\\Developing\\Ryft\\Website-Main\\node_modules\\@next-auth\\mongodb-adapter\\dist\\index.js:95:37)\n' +        
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async acc.<computed> (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\core\\errors.js:92:16)\n' +
    '    at async Object.session (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\core\\routes\\session.js:92:28)\n' +
    '    at async NextAuthHandler (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\core\\index.js:65:16)\n' +
    '    at async NextAuthNextHandler (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\next\\index.js:40:7)\n' +
    '    at async auth (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:18:12)\n' +
    '    at async Object.apiResolver (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next\\dist\\server\\api-utils.js:102:9)\n' +
    '    at async DevServer.handleApiRequest (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next\\dist\\server\\next-server.js:1014:9)',    
  name: 'TypeError'
}
[next-auth][error][SESSION_ERROR] 
https://next-auth.js.org/errors#session_error Cannot read properties of undefined (reading 'getUser') TypeError: Cannot read properties of undefined (reading 'getUser')
    at getSessionAndUser (E:\Developing\Ryft\Website-Main\node_modules\@next-auth\mongodb-adapter\dist\index.js:95:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async acc.<computed> (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\errors.js:92:16)
    at async Object.session (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\routes\session.js:92:28)
    at async NextAuthHandler (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\index.js:65:16)
    at async NextAuthNextHandler (E:\Developing\Ryft\Website-Main\node_modules\next-auth\next\index.js:40:7)
    at async auth (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:18:12)
    at async Object.apiResolver (E:\Developing\Ryft\Website-Main\node_modules\next\dist\server\api-utils.js:102:9)
    at async DevServer.handleApiRequest (E:\Developing\Ryft\Website-Main\node_modules\next\dist\server\next-server.js:1014:9) {
  name: 'GetSessionAndUserError'
}
```

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
looks like you are using an outdated version of the Adapter.

See my previous comment https://github.com/nextauthjs/adapters/issues/296#issuecomment-962452333

you haven't followed the docs either.

**Comment by balazsorban44** [comment]
I think these should be opened as discussions instead next time. there is no hard evidence here that you have found a bug in the adapter. questions should be opened as discussions. that would help us with maintenance. hope you agree 🙏

**Comment by callumok2004** [comment]
Alright, I will keep that in mind for the future!

I am currently using the `@latest` version, so... I am pretty sure I am not using an outdated version, unless you can elaborate?

**Comment by callumok2004** [comment]
I have updated the repro repo.
https://github.com/callumok2004/nextjs-reproduction

**Comment by balazsorban44** [comment]
unfortunately the reproduction does not show the lock file or the installed adapter version.

**Comment by callumok2004** [comment]
Ok, I am using the latest version `@next` I was mistaken, I have updated the repo it now shows the `yarn.lock` file

**Comment by callumok2004** [comment]
Ok, so I cleared all cache and reinstalled everything and that seems to be fine now, but now it is redirecting to /api/auth/error even though no error is given?

![](https://i.imgur.com/FKBAczL.gif)

**Comment by balazsorban44** [comment]
already reported at https://github.com/nextauthjs/next-auth/issues/3106

**Comment by callumok2004** [comment]
Also just got this
```c
[next-auth][error][adapter_error_createUser] 
https://next-auth.js.org/errors#adapter_error_createuser cyclic dependency detected { 
  message: 'cyclic dependency detected',
  stack: 'Error: cyclic dependency detected\n' +
    '    at serializeObject (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:333:34)\n' +
    '    at serializeInto (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:947:17)\n' +
    '    at serializeObject (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:347:18)\n' +
    '    at serializeInto (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:947:17)\n' +
    '    at serializeObject (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:347:18)\n' +
    '    at serializeInto (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:947:17)\n' +
    '    at serializeObject (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:347:18)\n' +
    '    at serializeInto (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:947:17)\n' +
    '    at serializeObject (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:347:18)\n' +
    '    at serializeInto (E:\\Developing\\Ryft\\Website-Main\\node_modules\\bson\\lib\\bson\\parser\\serializer.js:729:17)',
  name: 'Error'
}
```
