### ISSUE TITLE
Fauna @next adapter: f.query is not a function

### ISSUE THREAD

**Issue by ccannell** [nextauthjs/adapters#299]
### Title

Fauna @next adapter: f.query is not a function

### How to reproduce ☕️

Using the next-auth-example with v4 and @next fauna adapter.

**package.json**
```json
"dependencies": {
    "@next-auth/fauna-adapter": "^0.2.2-next.15",
    "faunadb": "^4.4.1",
    "next": "^12.0.3",
    "next-auth": "^4.0.0-beta.6",
    "nodemailer": "^6.7.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sqlite3": "^5.0.2"
  },
```

**[...nextauth].js**
```javascript
import NextAuth from "next-auth";
import * as Fauna from "faunadb";
import { FaunaAdapter } from "@next-auth/fauna-adapter";

const client = new Fauna.Client({
  secret: process.env.FAUNA_SECRET,
  scheme: process.env.FAUNA_SCHEME,
  domain: process.env.FAUNA_DOMAIN,
  port: 8443,
});

export default NextAuth({
  providers: [
    {
      id: "intuit",
      name: "Intuit",
      clientId: process.env.INTUIT_ID,
      clientSecret: process.env.INTUIT_SECRET,
      type: "oauth",
      version: "2.0",
      params: { grant_type: "authorization_code" },
      wellKnown: process.env.INTUIT_DOMAIN,
      authorization: { params: { scope: "openid email profile" } },
      scope:
        "openid email profile phone address com.intuit.quickbooks.accounting",
      idToken: false,
      checks: ["pkce", "state"],
      profile(profile) {
        return {
          id: profile.sub,
          name: `${profile.givenName} ${profile.familyName}`,
          email: profile.email,
          emailVerified: profile.emailVerified,
          image: undefined,
        };
      },
    },
  ],

  adapter: FaunaAdapter({ faunaClient: client }),
  session: {
  },
  jwt: {
    encryption: true,
    verificationOptions: {
      algorithms: ["RS256"],
    },
    signingKey: {
      kty: "RSA",
      e: "AQAB",
      use: "sig",
      kid: "OPICPRD09182014",
      alg: "RS256",
      n: "<omitted>",
    },
  },
  pages: {
  },
  callbacks: {
  },
  events: {},
  theme: {
    colorScheme: "light",
  },
  debug: true,
});

```

### Your question/bug report 📓

I'm getting the following error.

```javascript
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error f.query is not a function TypeError: f.query is not a function
    at /Users/ccannell/code/magothy/next-auth-example/node_modules/@next-auth/fauna-adapter/dist/index.js:61:36
    at getUserByAccount (/Users/ccannell/code/magothy/next-auth-example/node_modules/@next-auth/fauna-adapter/dist/index.js:90:32)
    at acc.<computed> (/Users/ccannell/code/magothy/next-auth-example/node_modules/next-auth/core/errors.js:92:22)
    at Object.callback (/Users/ccannell/code/magothy/next-auth-example/node_modules/next-auth/core/routes/callback.js:82:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NextAuthHandler (/Users/ccannell/code/magothy/next-auth-example/node_modules/next-auth/core/index.js:103:28)
    at async NextAuthNextHandler (/Users/ccannell/code/magothy/next-auth-example/node_modules/next-auth/next/index.js:40:7)
    at async /Users/ccannell/code/magothy/next-auth-example/node_modules/next-auth/next/index.js:80:32
    at async Object.apiResolver (/Users/ccannell/code/magothy/next-auth-example/node_modules/next/dist/server/api-utils.js:102:9)
    at async DevServer.handleApiRequest (/Users/ccannell/code/magothy/next-auth-example/node_modules/next/dist/server/next-server.js:1014:9) {
  name: 'GetUserByAccountError'
}
```

The error is in the following function at line `const result = await f.query(expr);`. 

```javascript
function query(f, format) {
    return async function (expr) {
        var _a;
        try {
            const result = await f.query(expr);
            if (!result)
                return null;
            return format({ ...result.data, id: result.ref.id });
        }
        catch (error) {
            if (error.name === "NotFound")
                return null;
            if ((_a = error.description) === null || _a === void 0 ? void 0 : _a.includes("Number or numeric String expected"))
                return null;
            if (process.env.NODE_ENV === "test")
                console.error(error);
            throw error;
        }
    };
}
```

The inputs are:

```javascript
expr: {"let":[{"ref":{"match":{"index":"account_by_provider_and_provider_account_id"},"terms":["intuit","<omitted>"]}}],"in":{"if":{"exists":{"var":"ref"}},"then":{"get":{"ref":{"collection":"users"},"id":{"select":["data","userId"],"from":{"get":{"var":"ref"}}}}},"else":null}}
format: undefined
f: {"faunaClient":{"_observer":null,"_http":{"_adapter":{"type":"http2","_sessionMap":{},"_http2SessionIdleTime":500,"_closed":false},"_baseUrl":"https://graphql.us.fauna.com/graphql:8443","_secret":"<omitted>","_headers":{"X-FaunaDB-API-Version":"4","X-Driver-Env":"driver=javascript-4.4.1; runtime=nodejs-v14.18.1; env=unknown; os=darwin-20.6.0"},"_queryTimeout":null,"_lastSeen":null,"_timeout":60000}}}
```

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/docs/pull/97/files
