### ISSUE TITLE
Invalid `p.account.findUnique()` invocation with prisma

### ISSUE THREAD

**Issue by MattA-Official** [nextauthjs/adapters#327]
### Title

Invalid `p.account.findUnique()` invocation with prisma

### How to reproduce ☕️

next-auth: `4.0.0-beta.7`
@next-auth/prisma-adapter: `0.5.2-next.19`

/pages/api/[...nextauth].ts
```ts
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import { hasBetaAccess } from 'lib/backend-utils';
import { prisma } from 'lib/prisma';
import NextAuth from 'next-auth';
import Discord from 'next-auth/providers/discord';

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    Discord({
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      authorization: 'https://discord.com/api/oauth2/authorize?scope=identify+guilds',
      profile(profile) {
        let image_url: string;

        if (profile.avatar === null) {
          const defaultAvatarNumber = parseInt(profile.discriminator, 10) % 5;
          image_url = `https://cdn.discordapp.com/embed/avatars/${defaultAvatarNumber}.png`;
        } else {
          const format = profile.avatar.startsWith('a_') ? 'gif' : 'png';
          image_url = `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.${format}`;
        }

        return {
          id: profile.id,
          username: profile.username,
          discriminator: profile.discriminator,
          avatar: image_url,
          profile: {
            vanity: profile.id,
            user_id: profile.id,
          },
        };
      },
    }),
  ],
  callbacks: {
    async session({ session, user }) {
      return {
        ...session,
        user,
      };
    },
    async signIn({ user }) {
      // Check for a development environment
      if (process.env.NODE_ENV === 'development') return true;

      // Check if the user has access to the beta
      const betaUser = user.beta || (await hasBetaAccess(user.id));
      return betaUser ? true : '/?error=AccessDenied';
    },
  },
});
```

Account schema
```prisma
model Account {
  id                 String  @id @default(cuid()) @map("_id")
  userId             String  @map("user_id")
  type               String
  provider           String
  providerAccountId  String  @map("provider_account_id")
  refresh_token      String?
  access_token       String?
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String?
  session_state      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@map("accounts")
}
```

### Your question/bug report 📓

The bug below results from the above code. It is worth noting I am using **MongoDB** and not any sort of SQL.

```
Invalid `p.account.findUnique()` invocation in
C:\Users\folder\path\node_modules\@next-auth\prisma-adapter\dist\index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique({
           where: {
             provider_providerAccountId: {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~
               providerAccountId: '366652352125599744',
               provider: 'discord'
             }
           },
           select: {
             user: true
           }
         })

Unknown arg `provider_providerAccountId` in where.provider_providerAccountId for type AccountWhereUniqueInput. Available args:

type AccountWhereUniqueInput {
  id?: String
}
```

### Contributing  🙌🏽

Yes, I am

**Comment by MattA-Official** [comment]
This is similar to #288 but there are a few differences that are big enough to give me a reason to create a new issue.

**Comment by balazsorban44** [comment]
There is a separate MongoDB adapter. MongoDB with Prisma hasn't been tested.

**Comment by balazsorban44** [comment]
Sorry, closed by accident. Would be happy to add support/tests, but currently, I cannot speak of how to get this working. ALthough the issue doesn't seem to be MongoDB specific.

Could you see if it works without the mapping stuff?

**Comment by MattA-Official** [comment]
Currently testing over on https://github.com/TeamDmod/dmod/tree/prisma, the entire codebase is a mess so it's being rewritten. Just started work on integrating prisma as the ORM today.

I would be happy to help run some tests, and I will try to reproduce the issue in a clean project. I shall try without the mapping to snake_case tomorrow.

**Comment by ndom91** [comment]
So based off of your debug output, it doesn't look like your `Account` model has any other available `unique` fields to query on, even though the `[provider, providerAccountId]` is clearly defined in the schema.. :thinking: 

See:

```
Unknown arg `provider_providerAccountId` in where.provider_providerAccountId for type AccountWhereUniqueInput. Available args:

type AccountWhereUniqueInput {
  id?: String
}
```

However, looking through the docs, I see that you can optionally give `@unique` and `@@unique` values a specific name now to query by (https://www.prisma.io/docs/concepts/components/prisma-schema/names-in-underlying-database#constraint-and-index-names)

i.e. `@@unique([pageId, readerId], name: "bookmark_page_id_reader_id_key")`

You may also be able to use `findOne` instead

**Comment by mateonunez** [comment]
Same issue here, I'm using Google Provider with Prisma Adapter.

```
[next-auth][debug][adapter_getUserByAccount] {
  args: [
    { providerAccountId: '117367287917655988076', provider: 'google' }
  ]
}
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount 
Invalid `p.account.findUnique()` invocation in
/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  The table `(not available)` does not exist in the current database. {
  message: '\n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    '/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    '  The table `(not available)` does not exist in the current database.',
  stack: 'Error: \n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    '/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    '  The table `(not available)` does not exist in the current database.\n' +
    '    at cb (/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@prisma/client/runtime/index.js:38688:17)\n' +
    '    at async getUserByAccount (/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29)',
  name: 'Error'
}
```

**Comment by MattA-Official** [comment]
> Same issue here, I'm using Google Provider with Prisma Adapter.
> 
> ```
> error - unhandledRejection: Error: 
> Invalid `p.account.findUnique()` invocation in
> /Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:13
> 
>    8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
>    9 async getUserByAccount(provider_providerAccountId) {
>   10     var _a;
> → 11     const account = await p.account.findUnique(
>   The table `(not available)` does not exist in the current database.
> ```
> 

No, that looks like a different error. Have you made sure to run `npx prisma migrate`?

**Comment by mateonunez** [comment]
@MattA-Official yes, I've done. 

I'm sure that is the same issue. I'm mapping my tables and got this error.

```
[next-auth][debug][adapter_getUserByAccount] {
  args: [
    { providerAccountId: '117367287917655988076', provider: 'google' }
  ]
}
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount 
Invalid `p.account.findUnique()` invocation in
/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  The table `(not available)` does not exist in the current database. {
  message: '\n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    '/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    '  The table `(not available)` does not exist in the current database.',
  stack: 'Error: \n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    '/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    '  The table `(not available)` does not exist in the current database.\n' +
    '    at cb (/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@prisma/client/runtime/index.js:38688:17)\n' +
    '    at async getUserByAccount (/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29)',
  name: 'Error'
}
```

**Comment by mateonunez** [comment]
@MattA-Official yes, I've done.

I think is the same issue. I'm just mapping my models. But when the Google auth is finished, Prisma Provider got me that error.

**Comment by MattA-Official** [comment]
The error messages say two completely different things, it could be related, but I doubt it. The original one is where an individual field isn't unique for some reason. Your one is where the table itself doesn't exist in the database, which isn't a possible error with mongo as it doesn't check for these things.

**Comment by mateonunez** [comment]
@MattA-Official anyway this is what I got when I remove the `@unique` in Account model:

```
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `p.account.findUnique()` invocation in
/Users/mateonunez/Documents/dev/boilerplates/base-fullstack-javascript/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique({
           where: {
             provider_providerAccountId: {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~
               providerAccountId: '117367287917655988076',
               provider: 'google'
             }
           },
           select: {
             user: true
           }
         })

Unknown arg `provider_providerAccountId` in where.provider_providerAccountId for type AccountWhereUniqueInput. Available args:

type AccountWhereUniqueInput {
  id?: String
}
```

It seems the same output!

These are my Models:

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["dataProxy"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Account {
  id                String   @id @default(cuid())
  userId            String   @map("user_id")
  type              String
  provider          String
  providerAccountId String   @map("provider_account_id")
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?
  createdAt         DateTime @default(now()) @map(name: "created_at")
  updatedAt         DateTime @default(now()) @map(name: "updated_at")


  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@map("accounts")
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime? @map("email_verified")
  image         String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @default(now()) @map(name: "updated_at")

  accounts Account[]
  sessions Session[]

  @@map("users")
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique @map("session_token")
  userId       String   @map("user_id")
  expires      DateTime
  createdAt    DateTime @default(now()) @map(name: "created_at")
  updatedAt    DateTime @default(now()) @map(name: "updated_at")

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@map("sessions")
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now()) @map(name: "created_at")
  updatedAt  DateTime @default(now()) @map(name: "updated_at")

  @@map("verification_tokens")
}
```

**Comment by sonipranjal** [comment]
I have a similar issue when I added supabase DB connection string in environment variable.
- database successfully migrated
- seed is working
But when I try to login it throws an error saying credentials are wrong!

````js
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `p.account.findUnique()` invocation in


Please make sure to provide valid database credentials for the database server at `db.xyz.supabase.co`.
    at cb (/Users/pranjalsoni/Desktop/projects/course project/code-course-platform/node_modules/@prisma/client/runtime/index.js:38697:17)
    at async getUserByAccount (/Users/pranjalsoni/Desktop/projects/course project/code-course-platform/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29) {
  name: 'GetUserByAccountError',
  code: undefined

**Comment by ndom91** [comment]
@mateonunez you're model seems to be missing one crucial line from our default model, at the end of the `Account` section, please add: 
```js
@@unique([provider, providerAccountId])
```

We've manually told the prisma model that `provider__providerAccountId` should be unique, and yuo're model seems to be missing that, therefore the failed request there.

See: https://github.com/nextauthjs/adapters/blob/1923ebf1f69ee9c4549a9c80703d7d795da0827b/packages/prisma/prisma/schema.prisma#L36

**Comment by ndom91** [comment]
@MattA-Official the crux of your issue seems to be the same, right? That `@@unique([provider, providerAccountId])` isn't being applied, so to speak. 

I did some digging through the Prisma docs, and it seems in the case of MongoDB, you must create this `@@unique` compound index yourself - Prisma can't/doesn't (not sure) do it in Mongo yet.

See: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#mongodb-4

**Comment by sonipranjal** [comment]
Here is my models, I am not able to figure out what is going on 🥲
```js 
model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
  refresh_token      String? @db.Text
  access_token       String? @db.Text
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String? @db.Text
  session_state      String?
  oauth_token_secret String?
  oauth_token        String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  stripeId      String?   @unique
  isSubscribed  Boolean   @default(false)
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  courses       Course[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

**Comment by ndom91** [comment]
Soni, without any further information, it seems like prisma can't login to your supabase database. Are you sure the credentials are entered correctly? Does supabase require any sort of IP Whitelisting maybe?

**Comment by sonipranjal** [comment]
Hi @ndom91, thank you for your response.
- Yes, I have provided the correct credentials. That's why migrations are working, seeding is working, but the only problem is in next-auth.

**Comment by krishnaUIDev** [comment]
I am facing same issue, I did migrate `npx prisma migrate`.

 `  model Account {
    id                 String    @id @default(cuid())
    userId             String
    providerType       String
    providerId         String
    providerAccountId  String?
    refreshToken       String?
    accessToken        String?
    accessTokenExpires DateTime?
    createdAt          DateTime  @default(now())
    updatedAt          DateTime  @updatedAt
    user               User      @relation(fields: [userId], references: [id])
    @@unique([providerId, providerAccountId])
  }
`

**Comment by ndom91** [comment]
@krishnaUIDev can you provide more detail as well? i.e. your config and copy of the error msg, etc. Thanks!

@sonipranjal okay but it still seems that prisma is having issues. Can you successfully run `npx prisma studio` to open the database viewer UI thing? Does that connect successfully? If so, can you share how yuo're using that `p.account.findUnique()` exactly?
