### ISSUE TITLE
Dgraph getAdapter is not a function

### ISSUE THREAD

**Issue by danhab99** [nextauthjs/adapters#357]
### Title

Dgraph getAdapter is not a function

### How to reproduce ☕️

`pages/api/auth/[...nextauth].tsx`

```ts
import NextAuth from "next-auth";
import Providers from "next-auth/providers";

import * as DgraphAdapter from "@next-auth/dgraph-adapter";

const DGRAPH_ADAPTER_CONFIG = {
  authToken: process.env.DGRAPH_TOKEN || "",
  endpoint: `http${process.env.DGRAPH_SSL ? "s" : ""}://${
    process.env.DGRAPH_DOMAIN
  }:8080/graphql`,
};

const d = DgraphAdapter.DgraphAdapter(DGRAPH_ADAPTER_CONFIG);

export default NextAuth({
  providers: [
    Providers.Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
    }),
    Providers.Twitter({
      clientId: process.env.TWITTER_ID,
      clientSecret: process.env.TWITTER_SECRET,
    }),
    Providers.Facebook({
      clientId: process.env.FACEBOOK_ID,
      clientSecret: process.env.FACEBOOK_SECRET,
    }),
  ],

  adapter: d, // TypeError: adapter.getAdapter is not a function

  secret: process.env.COOKIE_SECRET,

  session: {
    maxAge: 30 * 24 * 60 * 60, // 30 days
    updateAge: 24 * 60 * 60, // 24 hours
  },

  pages: {
    signIn: "/auth/signin",
    signOut: "/auth/signout",
    error: "/auth/error", // Error code passed in query string as ?error=
  },
});
```

Dependencies:

```
"@next-auth/dgraph-adapter": "^1.0.2",
"next": "^12.0.3",
"next-auth": "^3.29.0",
```

### Your question/bug report 📓

How do I handle this bug?

```
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error TypeError: adapter.getAdapter is not a function
    at Object.callback (/home/dan/Documents/node/moldypages/node_modules/next-auth/dist/server/routes/callback.js:71:56)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Thy adapter only works with v4 of `next-auth` Please upgrade.

**Comment by danhab99** [comment]
Updating resolved the type errors. Closing
