### ISSUE TITLE
TypeError: prisma[Account].findOne is not a function

### ISSUE THREAD

**Issue by JakubKoralewski** [nextauthjs/adapters#81]
**Describe the bug**
On `next-auth` `3.1.0`.
Error is thrown on trying to login with OAuth provider (GitHub). This only started happening after I updated prisma to `2.15.0`.

**Steps to reproduce**
1. Update prisma to `2.15.0` and try to log in.

```
[next-auth][error][get_user_by_provider_account_id_error] TypeError: prisma[Account].findOne is not a function
    at D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:148:36
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:16:103)
    at _next (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:18:194)
    at D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:18:364
    at new Promise (<anonymous>)
    at D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:18:97
    at _getUserByProviderAccountId (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:159:44)
    at getUserByProviderAccountId (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:140:44)
    at D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\server\routes\callback.js:83:55
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\server\routes\callback.js:26:103)
    at _next (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\server\routes\callback.js:28:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
https://next-auth.js.org/errors#get_user_by_provider_account_id_error
[next-auth][error][oauth_callback_handler_error] Error: GET_USER_BY_PROVIDER_ACCOUNT_ID_ERROR
    at D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:156:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:16:103)
    at _next (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:18:194)
    at D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:18:364
    at new Promise (<anonymous>)
    at D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:18:97
    at _getUserByProviderAccountId (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:159:44)
    at getUserByProviderAccountId (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\adapters\prisma\index.js:140:44)
    at D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\server\routes\callback.js:83:55
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\server\routes\callback.js:26:103)
    at _next (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next-auth\dist\server\routes\callback.js:28:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
https://next-auth.js.org/errors#oauth_callback_handler_error
```

Related to https://github.com/nextauthjs/next-auth/issues/1099
I think the fix there is to use canary (branch?) Whatever the fix is, it's not in stable so I will include this issue, since someone else probably will if I don't 😄 

I did install `npm i next-auth@canary`, which allowed me to travel in time to the future once the issue is fixed and get `3.2.0`, and I confirm the issue is fixed there. It's still in stable though. Cherry-pick into stable maybe pls?

**Comment by j0hnm4r5** [comment]
I just ran into this issue today. Using Prisma, I was not able to define custom Model names, following the instructions laid out in the [documentation](https://next-auth.js.org/schemas/adapters).

**Comment by balazsorban44** [comment]
Question. Did you use the built-in (imported from `next-auth/adapters`) or the new (`@next-auth/prisma-adapter`) version? The new version doesn't support custom model names (yet?)

**Comment by j0hnm4r5** [comment]
Definitely the built-in `import Adapters from "next-auth/adapters";`. I didn't even know a new one existed!

**Comment by balazsorban44** [comment]
Yes, it is not yet released as stable.

Interesting that people are bumping into this issue. If you have a look at the source code here: https://github.com/nextauthjs/adapters/blob/canary/packages/prisma-legacy/src/index.js

there is not a single reference to `.findOne` anymore :shrug: 

Which version of `prisma` and `next-auth` are you using? Could cou try upgrading both to latest?

**Comment by bhatvikrant** [comment]
Even I am facing this issue, can someone lay down what are the steps for the workaround?

I am using: 
```json
"@next-auth/prisma-adapter": "^0.4.4-canary.64",
"@prisma/client": "^2.24.1",
"prisma": "^2.24.1",
"next": "latest",
"next-auth": "^3.26.1",
```


my [...nextauth].js looks like:
```tsx
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'
import { PrismaAdapter } from '@next-auth/prisma-adapter'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
export default NextAuth({
	// Configure one or more authentication providers
	providers: [
		Providers.GitHub({
			clientId: process.env.GITHUB_ID,
			clientSecret: process.env.GITHUB_SECRET
		})
		// ...add more providers here
	],

	// A database is optional, but required to persist accounts in a database
	database: process.env.DATABASE_URL,
	adapter: PrismaAdapter(prisma)
})

```

**Comment by ndom91** [comment]
Hey yall, are you still having this issue? Since the latest comments here, we've published the 4.0.0 stable release (as well as some minor updates :grin:). So if you're still having issues, please try with the latest version and check out the current docs, everything has been updated for v4. 

If you're then still not able to get it working, feel free to post back here. Otherwise we'll close this stale issue in a week or two :+1:
