### ISSUE TITLE
Module not found: Can't resolve '@next-auth/firebase-adapter'

### ISSUE THREAD

**Issue by Ugarz** [nextauthjs/adapters#99]
Hi there,

I'm currently trying to use Next-Auth.js as my main authentication system with the firebase adapter.
Following the documentation, I have installed and setup the `next-auth` module, then I added the `@next-auth/firebase-adapter`  and followed to use the adapter but my terminal is yelling at me.

```
error - ./pages/api/auth/[...nextauth].js:3:0
Module not found: Can't resolve '@next-auth/firebase-adapter'
  1 | import NextAuth from 'next-auth'
  2 | import Providers from 'next-auth/providers'
> 3 | import { FirebaseAdapter } from "@next-auth/firebase-adapter"
  4 | import firebase from "firebase-admin"
  5 |
  6 | console.log('YO', FirebaseAdapter)
event - compiled successfully
```

I am currently using 
- `next-auth: ^3.23.3`
- `@next-auth/firebase-adapter: 0.0.1-pr.18.41`

I am using a custom `jsconfig.json` like so but removing it and reverse my paths don't resolve my issue with the adapter.
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@components/*": ["components/*"],
      "@styles/*": ["styles/*"],
      "@lib/*": ["lib/*"]
    }
  }
}
```

Any idea ?

**Comment by balazsorban44** [comment]
could you try 0.0.2-pr.18.173 which is the actual newest version?

I hope we will soon be able to move to a less chaotic versions, but first I want to make sure all the current adapters have some tests at place, then we can merge things into the main/latest branch. Sorry 🙏

**Comment by Ugarz** [comment]
Hello again 😄 

Please do not apologize you are doing a really great job and I thank you for the time and effort you bring into this project 😁

Thank you for your suggestion, I managed to import the adapter !
The `v0.0.2-pr.18.173` solved my issue 👏

However, I still have an error fetching data from Twitch with my Login:

```
event - build page: /api/auth/[...nextauth]
wait  - compiling...
event - compiled successfully
undefined
[next-auth][error][firebase__get_user_by_provider_account_id_error]
https://next-auth.js.org/errors#firebase__get_user_by_provider_account_id_error TypeError: Cannot read property 'collection' of undefined
    at getUserByProviderAccountId (/mnt/d/dev/momentum/node_modules/@next-auth/firebase-adapter/dist/index.js:49:26)
    at acc.<computed> (/mnt/d/dev/momentum/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
    at Object.callback (/mnt/d/dev/momentum/node_modules/next-auth/dist/server/routes/callback.js:70:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
As you can see, an error occur when I'm trying to login with my Twitch account.
I have been looking in the library `@next-auth/firebase-adapter/dist/index.js:49:26` and the `client` (firestore) might not be defined or passed correctly.

> On the first image you can see I get the right `providerId` (Twitch) and my `providerAccountId` seems correct.
![debug](https://user-images.githubusercontent.com/6050079/119386752-41e5ea80-bcc8-11eb-90b6-66d7a4711795.jpg)

> Here you can see that I went to the modules to log some informations
![debug49](https://user-images.githubusercontent.com/6050079/119386753-427e8100-bcc8-11eb-816b-c9ccb3d51206.jpg)

> And here are the data I watch in debug mode
![not-defined](https://user-images.githubusercontent.com/6050079/119386755-43171780-bcc8-11eb-8cdf-acc11245d980.jpg)


Here is my `/pages/api/auth/[...nextauth].js` file
```js
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

// Adds the firebase adapter
import firebase from "firebase-admin"
import { FirebaseAdapter } from "@next-auth/firebase-adapter"


// Firebase configuration from project
const firebaseConfig = {
  apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  authDomain: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  databaseURL: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  projectId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  storageBucket: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  messagingSenderId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  appId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  measurementId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
};

let firestore;

// Initialize App
if(!firebase.apps.length) {
   firestore = firebase.initializeApp(firebaseConfig).firestore()
}
console.log(firestore)

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export default NextAuth({
  // https://next-auth.js.org/configuration/providers
  providers: [
    Providers.Twitch({
      clientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    })
  ],
  adapter: FirebaseAdapter(firestore),
  database: process.env.FIREBASE_DATABASE_URL
})
```

Can you spot something that could went wrong ?

**Comment by balazsorban44** [comment]
oh, right.. there are two methods currently untested, one of them being the method you faced an issue with... I don't have a full understanding of our account  linking functionality, so I am still learning about it, but I'll have a look soon then. I might have an idea.

In the meantime, thanks for the encouraging words, really helps! 😊

**Comment by balazsorban44** [comment]
So I added some tests for the account methods, and unfortunately, I cannot spot the problem, as all tests pass.

I am curious if somehow this section:
```js
let firestore;

// Initialize App
if(!firebase.apps.length) {
   firestore = firebase.initializeApp(firebaseConfig).firestore()
}
console.log(firestore)
```
is the problem.

**Comment by Ugarz** [comment]
Hello !

First i would like to thank you to help me in my journey 😁

I agree with you @balazsorban44 as 
```
[0] ?? "do something"
[0]
```
and
```
undefined ?? "do something"
do something
```
You solution seems to be better.

But now something diffrent is happening

```
[next-auth][error][firebase__get_user_by_provider_account_id_error]
https://next-auth.js.org/errors#firebase__get_user_by_provider_account_id_error Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/mnt/d/dev/onfire/node_modules/google-auth-library/build/src/auth/googleauth.js:174:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async GoogleAuth.getClient (/mnt/d/dev/onfire/node_modules/google-auth-library/build/src/auth/googleauth.js:551:17)
    at async GrpcClient._getCredentials (/mnt/d/dev/onfire/node_modules/google-gax/build/src/grpc.js:110:24)
    at async GrpcClient.createStub (/mnt/d/dev/onfire/node_modules/google-gax/build/src/grpc.js:269:23)
```

I manage to reproduce this behaviour separatly in a repo i have made to demonstrate a simple project with Next-Auth.js and the Firebase adapter [that you can find here](https://github.com/Ugarz/onfire).

**Comment by balazsorban44** [comment]
Don't know if relevant, your DATABASE_URL env variable has a typo (you wrote DATBASE). will check out your repro in more details

**Comment by balazsorban44** [comment]
UPDATE. After spinning up an example locally myself, I did find some issues. I am going to address them in a PR. For starters, we shouldn't be using `firebase-admin` :facepalm:

`npm install firebase`
then
```diff
- import firebase from "firebase-admin"
+ import firebase from "firebase/app"
+ import "firebase/firestore"
```

**Comment by balazsorban44** [comment]
@Ugarz I managed to publish and test locally, and I successfully logged in. Could you test if `0.0.2-canary.168` works for you?

**Comment by Ugarz** [comment]
Hello !

Good job spotting the `firebase-admin` thing !

I reproduced your suggestions : I switched to `0.0.2-canary.168` and i no longer get the `Could not load the default credentials` error.
However, I get something new, this is what I get when I try to login with my Twitch account
```
[next-auth][error][firebase__get_user_by_provider_account_id_error]
https://next-auth.js.org/errors#firebase__get_user_by_provider_account_id_error Error [FirebaseError]: Missing or insufficient permissions.
    at new FirestoreError (/mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:377:28)
    at fromRpcStatus (/mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:7165:12)
    at fromWatchChange (/mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:7380:35)
    at PersistentListenStream.onMessage (/mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:15321:27)
    at /mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:15254:30
    at /mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:15290:28
    at /mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:21957:20
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'permission-denied',
  toString: [Function (anonymous)]
}
[next-auth][error][oauth_callback_handler_error]
https://next-auth.js.org/errors#oauth_callback_handler_error FirebaseError: Missing or insufficient permissions.
    at new FirestoreError (/mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:377:28)
    at fromRpcStatus (/mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:7165:12)
    at fromWatchChange (/mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:7380:35)
    at PersistentListenStream.onMessage (/mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:15321:27)
    at /mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:15254:30
    at /mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:15290:28
    at /mnt/d/dev/onfire/node_modules/@firebase/firestore/dist/node-cjs/database-d95963f8-68270b95.js:21957:20
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  name: 'GetUserByProviderAccountIdError'
}
```

When I try to authenticate  with my Google account I get a frontend error
```
Erreur 400 : invalid_request
Missing required parameter: client_id
```

**Comment by balazsorban44** [comment]
The former error is coming from firebase, looks like some security rules issues. When I tested it, I did try it with no security rules enabled, which obviously isn't recommended. I wonder what security rules should be necessary. 🤔

**Comment by Ugarz** [comment]
Okay I was wondering if it came from the library or from firebase, you confirmed what I was thinking.
I'll dig this this evenning and come back later, thank you !

**Comment by Ugarz** [comment]
Hello !

# Firebase rules
So I digged a bit in firebase rules and authorised everything coming from the outside for now (as I'm here to test the connexion, I'll lock the rules later). It appears that firebase is responding something diffrent.

# Another error
I get an error while creating the user coming from the firebase adapter `TypeError: Cannot read property 'toDate'` of undefined.

```
[next-auth][error][firebase__create_user_error]
https://next-auth.js.org/errors#firebase__create_user_error TypeError: Cannot read property 'toDate' of undefined
    at Object.docSnapshotToObject (/mnt/d/dev/onfire/node_modules/@next-auth/firebase-adapter/dist/utils.js:20:40)
    at createUser (/mnt/d/dev/onfire/node_modules/@next-auth/firebase-adapter/dist/index.js:28:42)
    at async acc.<computed> (/mnt/d/dev/onfire/node_modules/next-auth/dist/adapters/error-handler.js:19:16)
    at async callbackHandler (/mnt/d/dev/onfire/node_modules/next-auth/dist/server/lib/callback-handler.js:151:14)
    at async Object.callback (/mnt/d/dev/onfire/node_modules/next-auth/dist/server/routes/callback.js:98:13)
```
> The full error stack

# Digging
I went to the modules to look more precisely where I could find something, I went to `firebase-adapter/dist/utils.js:20:40` and saw

![01](https://user-images.githubusercontent.com/6050079/120085055-5fa2bd80-c0d5-11eb-8fc8-b5269d80172b.jpg)

```
:: Hello its here
[next-auth][error][firebase__get_user_by_email_error]
https://next-auth.js.org/errors#firebase__get_user_by_email_error TypeError: Cannot read property 'toDate' of undefined
    at Object.querySnapshotToObject (/mnt/d/dev/onfire/node_modules/@next-auth/firebase-adapter/dist/utils.js:40:35)
    at getUserByEmail (/mnt/d/dev/onfire/node_modules/@next-auth/firebase-adapter/dist/index.js:45:42)
    at async acc.<computed> (/mnt/d/dev/onfire/node_modules/next-auth/dist/adapters/error-handler.js:19:16)
    at async callbackHandler (/mnt/d/dev/onfire/node_modules/next-auth/dist/server/lib/callback-handler.js:145:43)
    at async Object.callback (/mnt/d/dev/onfire/node_modules/next-auth/dist/server/routes/callback.js:98:13)
[next-auth][error][oauth_callback_handler_error]
https://next-auth.js.org/errors#oauth_callback_handler_error TypeError: Cannot read property 'toDate' of undefined
    at Object.querySnapshotToObject (/mnt/d/dev/onfire/node_modules/@next-auth/firebase-adapter/dist/utils.js:40:35)
    at getUserByEmail (/mnt/d/dev/onfire/node_modules/@next-auth/firebase-adapter/dist/index.js:45:42)
    at async acc.<computed> (/mnt/d/dev/onfire/node_modules/next-auth/dist/adapters/error-handler.js:19:16)
    at async callbackHandler (/mnt/d/dev/onfire/node_modules/next-auth/dist/server/lib/callback-handler.js:145:43)
    at async Object.callback (/mnt/d/dev/onfire/node_modules/next-auth/dist/server/routes/callback.js:98:13) {
  name: 'GetUserByEmailError'
}
```
I think the resource `doc.createTime` is not reachable because I do not see it in the `doc` object or in my firebase `users` collection.
I found my user in firebase and got the right values, but I did not have `createTime` nor `updateTime` so I added them but nothing changed.
![03](https://user-images.githubusercontent.com/6050079/120085380-f96b6a00-c0d7-11eb-8f3c-6264262a5645.jpg)

What do you think ?

**Comment by balazsorban44** [comment]
You don't seem to use the newest adapter version. See the source code:

https://github.com/nextauthjs/adapters/blob/canary/packages/firebase/src/utils.ts

I removed these dates, so you shouldn't be getting these.
